### PR TITLE
fix(core/link-to-dfn): wrap as code for all linking formats

### LINKED ISSUE #2500: Regression on IDL operation linking
```html
<section data-dfn-for="Foo" data-link-for="Foo">
  <h2><dfn>Foo</dfn> interface</h2>
  <pre class="idl">
  [Exposed=Window]
  interface Foo {
    attribute DOMString bar;
    void doTheFoo();
  };
  </pre>
  <p>The <dfn>bar</dfn> attribute, returns 🍺.</p>
  <p>The <dfn>doTheFoo()</dfn> method, returns nothing.</p>
  <p><a>doTheFoo</a><a>doTheFoo()</a><a>Foo.doTheFoo</a><a>Foo.doTheFoo()</a></p>
</section>
```

image

Different formats of linking gets different styling. A regression after #2484.

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #2500

### CODE REVIEW

File: tests/spec/core/link-to-dfn-spec.js [hunk 1]
```diff
@@ -25,9 +25,12 @@ describe("Core — Link to definitions", () => {
...
         <pre class="idl">
-          interface Request {};
+          interface Request {
+            Request clone();
+          };
         </pre>
-        <p id="codeWrap">A <a>Request</a> object.</p>
+        <p id="codeWrap">A <a>Request</a> object has a <dfn>clone</dfn> method.</p>
+        <p id="codeWrapMethod"><a>clone</a>, <a>clone()</a>, <a>Request.clone</a>, and <a>Request.clone()</a> are all same.</p>
         <p id="noCodeWrap">An instance of <a lt="Request">the request interface</a>.</p>
```
Comment (marcoscaceres) [inline tests/spec/core/link-to-dfn-spec.js]: Related... looks like this test is wrong. 
```suggestion
        <p id="noCodeWrap">An instance of <a data-lt="Request">the request interface</a>.</p>
```
