### PR TITLE
fix(core/show-people): more robust error checking

### LINKED ISSUE #3530: Missing 'p-org' hcard classes
## Important info

- URL to affected spec: https://w3c.github.io/media-playback-quality/
- ReSpec version: 26.6.6
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

The [source](https://github.com/w3c/media-playback-quality/blob/gh-pages/index.html) of this spec includes

```javascript
        editors: [
          {
            w3cid: 45389,
            name: 'Mounir Lamouri',
            company: 'Google',
          },
```

But the generated output has 
```html
<dd class="p-author h-card vcard" data-editor-id="45389"><span class="p-name fn">Mounir Lamouri</span> (Google) </dd>
```

Where the "Google" bit isn't marked up. [Another (Bikeshed) spec](https://www.w3.org/TR/media-capabilities/) has:

```html
<dd class="editor p-author h-card vcard" data-editor-id="45389"><span class="p-name fn">Mounir Lamouri</span> (<a class="p-org org" href="https://www.google.com/">Google Inc.</a>)
```

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #3530

This is more or less a rewrite of how people are handled/rendered. 

This adds more robust error checking.

### CODE REVIEW

File: src/core/templates/show-people.js [hunk 1]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+}
+
+/**
+ * @param {string} member
+ * @param {string} rawDate
+ * @param {number} index
+ * @param {string} hint
+ * @returns
+ */
+function validateDateMember(member, rawDate, index, hint) {
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:242]: Eventually, we would move this into utils to check other date things.

File: src/core/templates/show-people.js [hunk 2]
```diff
@@ -1,10 +1,29 @@
...
+ * @property {string} [Person.companyURL]
+ * @property {string} [Person.note]
+ * @property {string} [Person.retiredDate]
+ * @property {PersonExtras} [Person.extras]
+ *
+ * @typedef {object} PersonExtras
+ * @property {string} PersonExtras.name
+ * @property {string} [PersonExtras.class]
+ * @property {string} [PersonExtras.href]
+ */
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:19]: Any reason to move this up? (trying to keep the PR small to save us in future)

File: src/core/templates/show-people.js [hunk 3]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+    contents.push(html` (${companyElem})`);
+  }
+  if (person.note) contents.push(document.createTextNode(` (${person.note})`));
+  if (person.extras) {
+    person.extras
+      .map(extra => html`, ${renderExtra(extra)}`)
+      .reduce((contents, html) => {
+        contents.push(html);
+        return contents;
+      }, contents);
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:130]: (Might need prettier on this)
```suggestion
    contents.push(
      ...person.extras.map(extra => html`, ${renderExtra(extra)}`)
    );
```

File: src/core/templates/show-people.js [hunk 4]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+    >`;
+    contents.push(html` - ${l10n.until(time)} `);
+  }
+  const dd = html`<dd
+    class="editor p-author h-card vcard"
+    data-editor-id="${editorId}"
+  >
+    ${contents}
+  </dd>`;
+  return dd;
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:145]:
```suggestion
  return html`<dd
    class="editor p-author h-card vcard"
    data-editor-id="${editorId}"
  >
    ${contents}
  </dd>`;
```

File: src/core/templates/show-people.js [hunk 5]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+/**
+ * @param {Person} person
+ * @param {Number} index
+ * @returns
+ */
+function validatePerson(person, index) {
+  const hint =
+    "See [Person](https://respec.org/docs/#person) configuration for available options.";
+  if (!person.name) {
+    const msg = `Person object at index ${index} is missing required member "name"`;
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:165]:
```suggestion
    const msg = `Person object at index ${index} is missing required member "name".`;
```

File: src/core/templates/show-people.js [hunk 6]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+  const remainder = orcidId
+    .split("")
+    .slice(0, -1)
+    .filter(c => /\d/.test(c))
+    .map(Number)
+    .reduce((acc, c) => (acc + c) * 2, 0);
+  const lastDigitInt = (12 - (remainder % 11)) % 11;
+  const lastDigitShould = lastDigitInt === 10 ? "X" : String(lastDigitInt);
+  if (lastDigit !== lastDigitShould) {
+    const hint = `orcid "${orcidId}" has an invalid checksum`;
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:291]:
```suggestion
    const hint = `ORCID "${orcidId}" has an invalid checksum.`;
```

File: src/core/templates/show-people.js [hunk 7]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+        showError(`"extra" index ${index} is not an object.`, name, {
+          hint,
+        });
+        return false;
+      case !extra.hasOwnProperty("name"):
+        showError(
+          `\`PersonExtra\` object at index ${index} is missing required "name" member.`,
+          name,
+          { hint }
         );
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:221]: This validation feels a little too much TBH.

File: src/core/templates/show-people.js [hunk 8]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+/**
+ * @param {string} member
+ * @param {string} rawDate
+ * @param {number} index
+ * @param {string} hint
+ * @returns
+ */
+function validateDateMember(member, rawDate, index, hint) {
+  const date = new Date(rawDate);
+  const isValidDate = date.toString() !== "Invalid Date";
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:244]: Maybe also add a check for `YYYY-MM-DD` format using regex: `/\d{4}-\d{2}-\d{2}/`

File: src/core/templates/show-people.js (hunk 5 above)
Comment (sidvishnoi) [inline src/core/templates/show-people.js:165]: I'm not sure if `person object at index ${index}` is useful as an error message. The Person could be coming from either `respecConfig.editors`, `respecConfig.authors` or `respecConfig.formerEditors`.
We should either add the respecConfig key to the error message, or maybe render `JSON.stringify(person)` there.

File: src/core/templates/show-people.js [hunk 9]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
-      class="p-author h-card vcard"
-      data-editor-id="${editorid}"
-    ></dd>`;
-    const span = document.createDocumentFragment();
-    const contents = [];
-    if (p.mailto) {
-      contents.push(html`<a
-        class="ed_mailto u-email email p-name"
-        href="${`mailto:${p.mailto}`}"
+  const personName = [person.name]; // treated as opt-in HTML by hyperHTML
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply src/core/templates/show-people.js:92]: Yeah, for legacy reasons, it can be HTML :( We should track down the specs that do this and fix them.

File: src/core/templates/show-people.js [hunk 10]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+  const company = [person.company];
+  const editorId = person.w3cid ? parseInt(person.w3cid, 10) : null;
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply src/core/templates/show-people.js:94]: Yeah, parseInt seems a little excessive.

File: src/core/templates/show-people.js [hunk 11]
```diff
@@ -62,113 +81,217 @@ const orcidIcon = () => html`<svg
...
+  const contents = [];
+  if (person.mailto) {
+    contents.push(html`<a
+      class="ed_mailto u-email email p-name"
+      href="${`mailto:${person.mailto}`}"
+      >${personName}</a
+    >`);
+  } else if (person.url) {
+    contents.push(
+      html`<a class="u-url url p-name fn" href="${person.url}"
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply src/core/templates/show-people.js:104]: "full name" probably.

File: src/core/templates/show-people.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply src/core/templates/show-people.js:19]: The definition is used multiple times, so having it at the top is nicer... although, maybe we should move this to the TS types files instead? Will make this file smaller.

File: src/core/templates/show-people.js (hunk 3 above)
Comment (marcoscaceres) [reply src/core/templates/show-people.js:132]: Nice :)

File: src/core/templates/show-people.js (hunk 4 above)
Comment (marcoscaceres) [reply src/core/templates/show-people.js:147]: I like to keep this one as seperate variable. Having gone through this process already, it's annoying to debug otherwise.

File: src/core/templates/show-people.js (hunk 8 above)
Comment (marcoscaceres) [reply src/core/templates/show-people.js:246]: Good idea.

File: src/core/templates/show-people.js (hunk 7 above)
Comment (marcoscaceres) [reply src/core/templates/show-people.js:220]: I don't mind it, tbh. `PersonExtra` is rarely used, as we added it to support ORCID before we added the orcid member.

File: src/core/templates/show-people.js (hunk 5 above)
Comment (marcoscaceres) [reply src/core/templates/show-people.js]: Yeah, was thinking the same... I'll add the name of the property as an argument.

File: src/type-helper.d.ts [hunk 12]
```diff
@@ -180,3 +180,22 @@ enum W3CGroupType {
...
+  name?: string;
+  w3cid?: string|number;
+  mailto?: string;
+  url?: string;
+  orcid?: string;
+  company?: string;
+  companyURL?: string;
+  note?: string;
+  retiredDate?: string;
+  extras?: PersonExtras;
```
Comment (sidvishnoi) [inline src/type-helper.d.ts:194]: I was hoping TypeScript to catch this 🤔 
```suggestion
  extras?: PersonExtras[];
```

File: src/type-helper.d.ts [hunk 13]
```diff
@@ -180,3 +180,22 @@ enum W3CGroupType {
   "ig",
   "wg",
 }
+
+type Person = {
+  name?: string;
```
Comment (sidvishnoi) [inline src/type-helper.d.ts:185]:
```suggestion
  name: string;
```

File: src/type-helper.d.ts [hunk 14]
```diff
@@ -180,3 +180,22 @@ enum W3CGroupType {
...
+  w3cid?: string|number;
```
Comment (sidvishnoi) [inline src/type-helper.d.ts:186]:
```suggestion
  w3cid?: string | number;
```

File: src/type-helper.d.ts (hunk 13 above)
Comment (marcoscaceres) [reply src/type-helper.d.ts:185]: oops

File: src/core/templates/show-people.js [hunk 15]
```diff
@@ -62,113 +68,227 @@ const orcidIcon = () => html`<svg
...
- *
- * @param {Person[]} persons
+ * @param {Conf} conf
+ * @param {string} propName - the name of the property of the people to render.
  */
-export default function showPeople(persons = []) {
+export default function showPeople(conf, propName) {
+  // nothing to show...
+  const people = conf[propName];
+  if (!Array.isArray(people) || !people.length) return;
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:77]:
```suggestion
  const people = conf[propName];
  if (!Array.isArray(people) || !people.length) return;   // nothing to show...
```

File: src/core/templates/show-people.js [hunk 16]
```diff
@@ -62,113 +68,226 @@ const orcidIcon = () => html`<svg
...
- * @property {string} [PersonExtras.href]
- *
- * @param {Person[]} persons
+ * @param {Conf} conf
+ * @param {string} propName - the name of the property of the people to render.
  */
-export default function showPeople(persons = []) {
+export default function showPeople(conf, propName) {
+  const people = conf[propName];
+  if (!Array.isArray(people) || !people.length) return;   // nothing to show...
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:76]:
```suggestion
  if (!Array.isArray(people) || !people.length) return; // nothing to show...
```

File: src/core/templates/show-people.js [hunk 17]
```diff
@@ -62,113 +68,226 @@ const orcidIcon = () => html`<svg
...
+  });
+}
+
+/**
+ *
+ * @param {Person} person
+ * @param {number} index
+ * @returns {boolean}
+ */
+function validateAndCanonicalizeOrcid(person, index) {
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:257]: Should send in the preamble here too.

File: src/core/templates/show-people.js [hunk 18]
```diff
@@ -62,113 +68,226 @@ const orcidIcon = () => html`<svg
...
+  if (orcidUrl.origin !== "https://orcid.org") {
+    const hint = `The origin should be "https://orcid.org", not "${orcidUrl.origin}"`;
+    showError(msg, name, { hint });
+    return false;
+  }
+
+  // trailing slash would mess up checksum
+  const orcidId = orcidUrl.pathname.slice(1).replace(/\/$/, "");
+  if (!/^\d{4}-\d{4}-\d{4}-\d{3}(\d|X)$/.test(orcidId)) {
+    const hint = `ORCIDs have the format "1234-1234-1234-1234", not "${orcidId}"`;
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:271]:
```suggestion
    const hint = `ORCIDs have the format "1234-1234-1234-1234", not "${orcidId}."`;
```

File: src/core/templates/show-people.js [hunk 19]
```diff
@@ -62,113 +68,226 @@ const orcidIcon = () => html`<svg
...
+/**
+ *
+ * @param {Person} person
+ * @param {number} index
+ * @returns {boolean}
+ */
+function validateAndCanonicalizeOrcid(person, index) {
+  const { orcid } = person;
+  const orcidUrl = new URL(orcid, "https://orcid.org/");
+  const msg = `"${person.orcid}" at index ${index} has an invalid ORCID`;
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:260]:
```suggestion
  const msg = `"${person.orcid}" at index ${index} has an invalid ORCID.`;
```

File: src/core/templates/show-people.js [hunk 20]
```diff
@@ -62,113 +68,226 @@ const orcidIcon = () => html`<svg
...
 
-    // @ts-ignore: hyperhtml types only support Element but we use a DocumentFragment here
-    html.bind(span)`${contents}`;
-    dd.appendChild(span);
-    return dd;
-  }
+    if (person.companyURL && !person.company) {
+      const msg = `${preamble} Has a "\`companyURL\`" property but no "\`company\`" property.`;
+      showWarning(msg, name, {
+        hint: `Please add a "\`company\`" property. ${hint}`,
```
Comment (marcoscaceres) [inline src/core/templates/show-people.js:199]:
```suggestion
        hint: `Please add a "\`company\`" property. ${hint}.`,
```

**Comment by marcoscaceres** [comment]
@sidvishnoi, I think I've addressed everything now. All good to merge?

File: src/core/templates/show-people.js [hunk 21]
```diff
@@ -62,113 +68,227 @@ const orcidIcon = () => html`<svg
...
-export default function showPeople(persons = []) {
+export default function showPeople(conf, propName) {
+  const people = conf[propName];
+  if (!Array.isArray(people) || !people.length) return; // nothing to show...
+
+  const validatePerson = personValidator(propName);
+  return people.filter(validatePerson).map(personToHTML);
+}
+
+function personToHTML(person) {
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:82]:
```suggestion
/**
 * @param {Person} person
 */
function personToHTML(person) {
```

File: tests/spec/core/show-people-spec.js [hunk 22]
```diff
@@ -0,0 +1,240 @@
...
+    it("generates the person's url", () => {
+      const render = html.bind(document.createDocumentFragment());
+      const person = { name: "name", url: "https://some.url" };
+      const result = render`${showPeople({ people: [person] }, "people")}`;
+      const a = result.querySelector("dd > a[href='https://some.url']");
+      expect([...a.classList]).toEqual(["u-url", "url", "p-name", "fn"]);
+      expect(a.textContent).toBe(person.name);
+    });
+
+    it("generates prefers email over their URL", () => {
```
Comment (sidvishnoi) [inline tests/spec/core/show-people-spec.js:75]:
```suggestion
    it("prefers email over their URL", () => {
```

File: tests/spec/core/show-people-spec.js [hunk 23]
```diff
@@ -0,0 +1,240 @@
+import { html } from "../../../src/core/import-maps.js";
```
Comment (sidvishnoi) [inline tests/spec/core/show-people-spec.js:1]: Maybe we can move this file to unit tests folder (`tests/unit/core/show-people-spec.js`)?

File: src/type-helper.d.ts [hunk 24]
```diff
@@ -180,3 +180,22 @@ enum W3CGroupType {
   "ig",
   "wg",
 }
+
+type Person = {
```
Comment (sidvishnoi) [inline src/type-helper.d.ts:184]: Lets also add `editors`, `authors` and `formerEditors` to `Conf`

File: tests/spec/core/show-people-spec.js (hunk 23 above)
Comment (marcoscaceres) [reply tests/spec/core/show-people-spec.js:1]: Sure.

File: src/type-helper.d.ts (hunk 24 above)
Comment (sidvishnoi) [reply src/type-helper.d.ts:184]: Would also require:
```diff
- @param {string} propName
+ @param {"editors" | "authors" | "formerEditors"} propName
```

File: src/core/templates/show-people.js [hunk 25]
```diff
@@ -62,113 +68,229 @@ const orcidIcon = () => html`<svg
...
- * @property {PersonExtras} [Person.extras]
- *
- * @typedef {object} PersonExtras
- * @property {string} PersonExtras.name
- * @property {string} [PersonExtras.class]
- * @property {string} [PersonExtras.href]
- *
- * @param {Person[]} persons
+ * @param {Conf} conf
+ * @param {string} propName - the name of the property of the people to render.
```
Comment (sidvishnoi) [inline src/core/templates/show-people.js:72]:
```suggestion
 * @param {"editors" | "authors" | "formerEditors"} propName - the name of the property of the people to render.
```

**Review by sidvishnoi — APPROVED** [review]
🚢

**Comment by marcoscaceres** [comment]
Woot! thanks for the review @sidvishnoi!
