### PR TITLE
fix(w3c): improve license + unofficial status support

### LINKED ISSUE #3064: Unofficial specs using CC-BY
In a spec with `specStatus: "unofficial", license: "cc-by"`, ReSpec emits an error:

> You cannot use license "`cc-by`" with W3C Specs. Please set `respecConfig.license: "w3c-software-doc"` instead.

In the documentation for [specStatus](https://github.com/w3c/respec/wiki/specStatus), `unofficial` is:

> An unofficial draft. Use this if you're producing a document outside of W3C but want to use styles that match those of W3C specifications, for instance to propose a new document while hosting it on your own server. Note that this automatically licenses the content under CC-BY v3.0. If you want a different copyright, you will need to set the various copyright configuration options.	

(BTW, CC-BY v3.0 should probably be CC-BY v4.0 here. See [the code here](https://github.com/w3c/respec/blob/b623ed094e11b251c9b6c03bf347afb3359ffd23/src/w3c/templates/headers.js#L288).)

Since "unofficial" is considered a document *outside* of W3C and the default license is CC-BY, maybe ReSpec shouldn't emit this [error](https://github.com/w3c/respec/blob/2bcffb680c784b0fe65c606bc08c5e22fc797872/src/w3c/headers.js#L238-L241)?

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #3064 

It no longer hard codes cc-by into the template, which was overriding license selection.

### CODE REVIEW

File: tests/spec/w3c/headers-spec.js [hunk 1]
```diff
@@ -1001,22 +1001,103 @@ describe("W3C — Headers", () => {
...
+        "https://creativecommons.org/licenses/by/4.0/legalcode"
+      );
+    });
+
+    it("falls back to cc-by when license is unknown and spec status is unofficial", async () => {
+      const ops = makeStandardOps();
+      ops.config = {
+        shortName: "whatever",
+        specStatus: "unofficial",
+        licenses: "not a thing",
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js:1026]:
```suggestion
        license: "not a thing",
```

File: src/w3c/headers.js [hunk 2]
```diff
@@ -243,14 +256,29 @@ export function run(conf) {
   if (conf.isUnofficial && !Array.isArray(conf.logos)) {
     conf.logos = [];
   }
+  if (conf.isUnofficial) {
+    if (conf.license && !licenses.has(conf.license)) {
```
Comment (sidvishnoi) [inline src/w3c/headers.js:260]: Should we check this regardless of `conf.isUnofficial`?

File: src/w3c/headers.js [hunk 3]
```diff
@@ -385,7 +413,7 @@ export function run(conf) {
       !conf.isNoTrack &&
       !conf.isSubmission
     ) {
-      const msg = "Document on track but no previous version.";
```
Comment (sidvishnoi) [inline src/w3c/headers.js:388]: This one is probably not desired. All other `msg` end with full-stop.

File: src/w3c/templates/headers.js [hunk 4]
```diff
@@ -282,25 +282,23 @@ function renderCopyright(conf) {
...
-          )}.
-        </p>`
-    : conf.overrideCopyright
-    ? [conf.overrideCopyright]
-    : renderOfficialCopyright(conf);
+  if (conf.isUnofficial && conf.licenseInfo) {
+    return html`<p class="copyright">
+      This document is licensed under a
+      ${linkLicense(
+        `${conf.licenseInfo.name}`,
```
Comment (sidvishnoi) [inline src/w3c/templates/headers.js:294]:
```suggestion
        conf.licenseInfo.name,
```

File: tests/spec/w3c/headers-spec.js [hunk 5]
```diff
@@ -1001,22 +1001,103 @@ describe("W3C — Headers", () => {
...
 
-  describe("license - w3c-software-doc", () => {
+  describe("license configuration", () => {
+    it("defaults to cc-by when spec status is unofficial", async () => {
+      const ops = makeStandardOps();
+      ops.config = {
+        shortName: "whatever",
+        specStatus: "unofficial",
+        editors: [{ name: "foo" }],
+      };
```
Comment (sidvishnoi) [inline tests/spec/w3c/headers-spec.js:1011]:
```suggestion
      const ops = makeStandardOps({
        shortName: "whatever",
        specStatus: "unofficial",
      });

```

File: tests/spec/w3c/headers-spec.js [hunk 6]
```diff
@@ -1241,18 +1322,6 @@ describe("W3C — Headers", () => {
         /XXX\s+&\s+the\s+Contributors\s+to\s+the/
       );
     });
-    it("takes additionalCopyrightHolders into account when spec is unofficial", async () => {
```
Comment (sidvishnoi) [inline tests/spec/w3c/headers-spec.js:1244]: Could this be a breaking change? I'm not sure I follow the rationale behind this.

Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js:1244]: `additionalCopyrightHolders` was being used incorrectly here. It was being used as equivalent of the  `replaceCopyright` option. I think that was a oversight - specially for "unofficial" docs. I checked specs using `additionalCopyrightHolders` and none are "unofficial".

File: src/w3c/headers.js (hunk 3 above)
Comment (marcoscaceres) [reply src/w3c/headers.js:388]: This appears to be a bug in core UI:

https://github.com/w3c/respec/blob/49ddeac2e88a635032d65f21a7244350512c1c14/src/core/ui.js#L278

It adds a "." to the hint. We probably don't want that regardless in i18n'zed contexts. I'll remove it.

File: tests/spec/w3c/headers-spec.js (hunk 5 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js:1011]: forgot about this :P

File: src/w3c/headers.js (hunk 2 above)
Comment (marcoscaceres) [reply src/w3c/headers.js:260]: yes, but I want to do that as a followup. I'm just interested in dealing with unofficial for now... eventually we need to rip out all the unofficial stuff from the W3C profile. None of that stuff should be here.

File: tests/spec/w3c/headers-spec.js (hunk 5 above)
Comment (sidvishnoi) [reply tests/spec/w3c/headers-spec.js]: Also the ones below

File: src/w3c/headers.js (hunk 3 above)
Comment (marcoscaceres) [reply src/w3c/headers.js:388]: Just in case, fix is now here: https://github.com/w3c/respec/pull/3310/files#diff-b1ee7df5d4991f7198879953fab78023c1ed2dcb5e6d45b2f8994e50d3459c24

File: tests/spec/w3c/headers-spec.js (hunk 5 above)
Comment (sidvishnoi) [reply tests/spec/w3c/headers-spec.js]: I'll fix the rest..

**Review by sidvishnoi — APPROVED** [review]
