### PR TITLE
fix!(w3c/style): override color-scheme with meta tag

### LINKED ISSUE #4687: How to deal with custom styles in dark mode?
## Description of problem

**URL to affected spec or repo:**

* Code: https://github.com/w3c/bp-i18n-specdev/pull/130
* Preview: https://deploy-preview-130--bp-i18n-specdev.netlify.app/

**What happened (e.g., it crashed)?:**

1. Open https://deploy-preview-130--bp-i18n-specdev.netlify.app/#lang_misc when the system is in light mode.
2. Select 'dark' in the lower left corner of the spec.
3. The colour is incorrect.

If the OS is in dark mode, the colour is correct.

**Expected behavior (e.g., it shouldn't crash):**

Colours should follow the `@media (prefers-color-scheme: dark)` media query.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Removes the opt in `respecConfig.darkMode` option, allowing HTML's  meta tag to be used instead.

### CODE REVIEW

File: src/w3c/style.js [hunk 1]
```diff
@@ -114,28 +114,30 @@ export function run(conf) {
...
-    // As required by W3C Pub Rules.
-    sub("beforesave", styleMover(darkModeStyleUrl));
+  /** @type HTMLMetaElement */
+  let colorScheme = document.querySelector("head meta[name=color-scheme]");
+  if (!colorScheme) {
+    colorScheme = html`<meta name="color-scheme" content="light dark" />`;
+    document.head.appendChild(colorScheme);
   }
+  const darkModeStyleUrl = getStyleUrl("dark.css");
+  const css = `:root {
```
Comment (marcoscaceres) [inline src/w3c/style.js:124]: If the meta tag sets this, any idea why this is needed, @sidvishnoi ? Just for completeness?

**Comment by sidvishnoi** [comment]
Let's still keep this behind darkMode flag for a while? It was added to prevent specs that use custom styles to opt-in after getting adapted.

**Comment by marcoscaceres** [comment]
I still don’t feel that a configuration flag is the right approach. It should then be we inject the meta to default to “light”, allowing spec authors to then opt into light/dark. 

Then the transitional path is that we announce this, and give everyone a year to check their specs before switching.

**Comment by marcoscaceres** [comment]
Should be good to go now, @sidvishnoi.

File: src/w3c/style.js (hunk 1 above)
Comment (sidvishnoi) [reply src/w3c/style.js:125]: I think we can remove this now. It existed before I added that meta tag. Though, check if any browser support differences.

File: src/w3c/style.js [hunk 2]
```diff
@@ -114,18 +114,24 @@ export function run(conf) {
...
+    document.head.appendChild(colorScheme);
+  }
+  const css = `:root {
+    color-scheme: ${colorScheme.content};
+  }`;
+  document.head.appendChild(
+    html`<style id="respec-color-scheme-declaration">
+      ${css}
+    </style>`
+  );
```
Comment (marcoscaceres) [inline src/w3c/style.js:132]:
```suggestion
```

File: tests/spec/w3c/style-spec.js [hunk 3]
```diff
@@ -238,6 +250,22 @@ describe("W3C - Style", () => {
...
+    /** @type HTMLStyleElement? */
+    const styleElem = doc.querySelector(
+      "style#respec-color-scheme-declaration"
+    );
+    expect(styleElem).toBeTruthy();
+
+    // Check if the style content includes the correct color-scheme value
+    const actualCSSContent = styleElem?.textContent;
+    expect(actualCSSContent?.includes("color-scheme: dark light")).toBeTruthy();
+  });
```
Comment (marcoscaceres) [inline tests/spec/w3c/style-spec.js:267]:
```suggestion
```

File: tests/spec/w3c/style-spec.js [hunk 4]
```diff
@@ -238,6 +250,7 @@ describe("W3C - Style", () => {
     expect(linkBase.nextElementSibling).toBe(linkDarkMode);
   });
 
+
```
Comment (marcoscaceres) [inline tests/spec/w3c/style-spec.js:253]:
```suggestion
```

**Review by sidvishnoi — APPROVED** [review]
