### PR TITLE
fix(core/xref): duplicate references

### LINKED ISSUE #2180: Regression: normative biblio things end up in informative section
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/#references
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
Duplicate bibliographical entries:
https://w3c.github.io/payment-request/#references

DOM and dom, weidl and WEBIDL

But what I was expecting?:

For there to be no duplicates. 

Optional, steps to reproduce:
 1. See https://w3c.github.io/payment-request/#references

### PR DESCRIPTION
**Pull request by marcoscaceres**
Fixes #2180

### CODE REVIEW

File: src/core/xref.js [hunk 1]
```diff
@@ -241,12 +241,24 @@ function addDataCiteToTerms(results, xrefMap, conf) {
 
       // add specs for citation (references section)
       const closestInform = elem.closest(nonNormativeSelector);
-      if (
```
Comment (sidvishnoi) [inline src/core/xref.js]: we better split this into it's own function

File: src/core/xref.js [hunk 2]
```diff
@@ -241,12 +241,24 @@ function addDataCiteToTerms(results, xrefMap, conf) {
...
+      const closestNormative = elem.closest(".normative");
+      let isNormative = false;
+      if (!closestInform) {
+        isNormative = true;
+      } else if (elem === closestNormative) {
```
Comment (sidvishnoi) [inline src/core/xref.js]: maybe merge this in `if` statement above?
``` js
if (!closestInform || elem === closestNormative) {
  isNormative = true;
} else if (// ...
```

Comment (marcoscaceres) [reply src/core/xref.js]: Good idea - will add. Could we treat this a nit (i.e., pre-approve this PR)? I’ve got a slight emergency with as this is blocking publications 😓
