### PR TITLE
fix(core/examples): Correct href links

### LINKED ISSUE #2033: Example link fragments are crazy long
## Important info

* URL to affected spec:
https://w3c.github.io/screen-orientation/#ex-1-example-1-script-var-show-function-console-log-orientation-type-is-screen-orientation-type-console-log-orientation-angle-is-screen-orientation-angle-screen-orientation-addeventlistener-change-show-window-onload-show-script-button-onclick-screen-orientation-unlock-unlock-button-button-onclick-screen-orientation-lock-portrait-lock-to-portrait-button-button-onclick-screen-orientation-lock-landscape-lock-to-landscape-button

## Description of problem

What happened (e.g., it crashed)?: 
Links on examples without a title are crazy long... see above. Seems to be using the textContent to generate the fragment, instead of just "#ex-2" or "#example-2". 
 
But what I was expecting?:

Something less insane. 

Optional, steps to reproduce:
 
```HTML 
<aside class="example">

</aside>
```

### PR DESCRIPTION
**Pull request by Johanna-hub**
fixes #2033 

For feedback 🙂

### CODE REVIEW

File: tests/spec/core/examples-spec.js [hunk 1]
```diff
@@ -86,4 +86,20 @@ describe("Core — Examples", () => {
     // id got relocated from the pre to the div
     expect(example.localName).toBe("div");
   });
+  it("makes correct links", async () => {
+    const body = `
+      <aside class="example">
+      <p>This is a very long link</p>
```
Comment (marcoscaceres) [inline tests/spec/core/examples-spec.js]:
```suggestion
        <p>This is a very long link</p>
```

**Comment by Johanna-hub** [comment]
> We discussed switching these to "example-1" and "example-1-whatever-the-title-is".

I have now made this change and also changed the tests where needed.

File: src/core/examples.js [hunk 2]
```diff
@@ -50,7 +49,13 @@ export function run(conf) {
       ++number;
       const div = makeTitle(conf, example, number, report);
       example.prepend(div);
-      const id = addId(example, `ex-${number}`, title);
+      if (title) {
+        addId(example, `example-${number}`, title); // title gets used
+      } else {
+        // use the number as the title... so, e.g., "ex-5"
```
Comment (marcoscaceres) [inline src/core/examples.js]:
```suggestion
        // use the number as the title... so, e.g., "example-5"
```
