### PR TITLE
fix: link-to-dfn module may report a TypeError

### LINKED ISSUE #1666: link-to-dfn module may report a TypeError
## Important info

* URL to affected spec: https://wicg.github.io/InputDeviceCapabilities/
* ReSpec version: 20.10.4
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
TypeError reported by Respec while generating the spec
```
TypeError​columnNumber: 9296
​fileName: "https://www.w3.org/Tools/respec/respec-w3c-common"​lineNumber: 442​
message: "t[0] is undefined"​
stack: "
e.run/<@https://www.w3.org/Tools/respec/respec-w3c-common:442:9296
each@https://www.w3.org/Tools/respec/respec-w3c-common:1:81330
each@https://www.w3.org/Tools/respec/respec-w3c-common:1:80010
e.run@https://www.w3.org/Tools/respec/respec-w3c-common:442:8391
s/</<@https://www.w3.org/Tools/respec/respec-w3c-common:1:63855
s/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:63654
e.runAll@https://www.w3.org/Tools/respec/respec-w3c-common:1:63264
"​__proto__: Object { stack: "", … } require.js:1
  e.runAll require.js:1
```

But what I was expecting?:
No error... or a more meaningful error if the spec needs to be fixed.

Error is triggered because the code tries to access [`linkTargets[0]`](https://github.com/w3c/respec/blob/79d0497ecb1a82f953d27526f7de429641c1da36/src/core/link-to-dfn.js#L118) whereas the array is empty.

### PR DESCRIPTION
**Pull request by sidvishnoi**
- Make CG template complain if `conf.wg` is not set (`pub("error")`)
- Prevent `linkTargets` from crashing when it encounters an empty `<a>`
- Closes #1666

### CODE REVIEW

File: src/core/link-to-dfn.js [hunk 1]
```diff
@@ -108,15 +108,15 @@ export function run(conf, doc, cb) {
       }
       return false;
     });
-    if (!foundDfn) {
+    if (!foundDfn && linkTargets.length != 0) {
```
Comment (marcoscaceres) [inline src/core/link-to-dfn.js]: nit: !==

File: src/w3c/headers.js [hunk 2]
```diff
@@ -537,6 +537,9 @@ export function run(conf) {
       "If one of '`wg`', '`wgURI`', or '`wgPatentURI`' is an array, they all have to be."
     );
   }
+  if (conf.isCGBG && !conf.wg) {
+    pub("error", "`respecConfig.wg` is required.");
```
Comment (marcoscaceres) [inline src/w3c/headers.js]: Nit: link to wiki for `wg`

Comment (marcoscaceres) [reply src/w3c/headers.js]: might want to give a little more help here too.  "`wg` configuration option is required for CG docs (e.g., "Web Incubator Community Group")."

File: src/w3c/headers.js [hunk 3]
```diff
@@ -537,6 +537,13 @@ export function run(conf) {
       "If one of '`wg`', '`wgURI`', or '`wgPatentURI`' is an array, they all have to be."
     );
   }
+  if (conf.isCGBG && !conf.wg) {
+    pub(
+      "error",
+      "[`wg`](https://github.com/w3c/respec/wiki/wg)" +
+        " configuration option is required for CG documents."
```
Comment (marcoscaceres) [inline src/w3c/headers.js]: Nit: this applies to BG documents too, so better to say “required for this kind of document”.
