### PR TITLE
fix(core/biblio): prevent SpecRef request if there are no refs

### LINKED ISSUE #1726: Prevent SpecRef request if there are no refs
If a request to SpecRef is sent that has no values in `refs`, such as `https://specref.herokuapp.com/bibrefs?refs=`, we gets lots of errors (like `Legacy SpecRef entries are not supported`) as SpecRef returns data that we don't want (or handle) and respec hangs.

TODO: 
1. Investigate why and when does it happen.
2. As a fix, if there are no `refs`, don't send a request.

### PR DESCRIPTION
**Pull request by sidvishnoi**
Fixes #1726

### CODE REVIEW

File: src/core/biblio.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ export async function updateFromNetwork(
   options = { forceUpdate: false }
 ) {
   // Update database if needed, if we are online
+  refs = refs.filter(ref => ref.trim());
```
Comment (marcoscaceres) [inline src/core/biblio.js]: nit: maybe move this above the comment?

Comment (marcoscaceres) [reply src/core/biblio.js]: oh, also, maybe make a new variable (cleanRefs)... best not to trash variables.
