### PR TITLE
fix(core/anchor-expander): convert nested header links to spans

### LINKED ISSUE #3136: Automatic link to sections should not embed links
## Important info

- URL to affected spec: https://w3c.github.io/mediacapture-main/getusermedia.html
- ReSpec version: 25.14.0
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**
The markup `<a href="#mediadevices></a>` which allows to create a human readable link to the said section creates invalid markup, because the heading of that section contains itself a link, which is then embedded in the resulting link (`<a href="#mediadevices" class="sec-ref">§&nbsp;<bdi class="secno">9.2 </bdi><a data-link-type="idl" href="#dom-mediadevices" class="internalDFN"><code><code>MediaDevices</code></code></a></a>`)

**Expected behavior (e.g., it shouldn't crash):**
ReSpec should strip existing links when embedding markup in a link.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #3136

### CODE REVIEW

File: tests/spec/core/anchor-expander-spec.js [hunk 1]
```diff
@@ -133,4 +133,32 @@ describe("Core - anchor-expander", () => {
...
+    `;
+    const ops = makeStandardOps({}, body);
+    const doc = await makeRSDoc(ops);
+    for (const exp of ["exp1", "exp2", "exp3", "exp4"]) {
+      const p = doc.getElementById(exp);
+      expect(p.querySelector("a a")).toBeNull();
+      const span = p.querySelector("span");
+      expect(span).toBeTruthy();
+      expect(span.textContent.trim()).toEqual("MediaDevices");
+      expect(span.attributes.length).toEqual(0);
```
Comment (sidvishnoi) [inline tests/spec/core/anchor-expander-spec.js:161]: Nit:
```suggestion
      expect(span.attributes).toHaveSize(0);
```

File: src/core/anchor-expander.js [hunk 2]
```diff
@@ -118,6 +118,14 @@ function processHeading(heading, a) {
   if (a.lastChild.nodeType === Node.TEXT_NODE) {
     a.lastChild.textContent = a.lastChild.textContent.trimEnd();
   }
+  // Replace all inner anchors for span elements (see bug #3136)
+  a.querySelectorAll("a").forEach(a => {
+    const span = renameElement(a, "span");
+    // Remove the old attributes
+    for (const attr of [...span.attributes]) {
```
Comment (sidvishnoi) [inline src/core/anchor-expander.js:125]: Nit: Maybe use forEach instead of creating a new array with [...]?

**Review by sidvishnoi — APPROVED** [review]
Few nits..
