### PR TITLE
fix(core/utils): removes attributes from dfn when calling makeSafeCopy

### LINKED ISSUE #3486: Automatic link to sub-sections duplicate definition markup
## Important info

- URL to affected spec: https://w3c.github.io/webrtc-pc/webrtc.html
- ReSpec version: 26.6.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem
The WebRTC spec uses automatic links to one of its subsection with `<a href="#rtcicetransport"></a>`.
This gets expanded with the full markup of the title of that section, including the `<dfn>` of the `RTCIceTransport` name (although as a `span dfn-type=interface` rather than a `dfn` element). That definition then gets wrapped into the dfn panel popup trigger - the panel never actually gets shown because the link takes precedence, but it doesn't make sense for the definition to be copied over, and with the latest accessibility improvements, it creates a situation where an element with `tabindex` gets embedded in a link, which the markup validator flags as an error.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #3486

### CODE REVIEW

File: tests/spec/core/anchor-expander-spec.js [hunk 1]
```diff
@@ -78,7 +78,8 @@ describe("Core - anchor-expander", () => {
     expect(doc.querySelector("#expansion *[id]")).toBeNull();
 
     const [firstSpan, secondSpan] = doc.querySelectorAll("#expansion a > span");
-    expect(firstSpan.title).toBe("pass");
+    // title get dropped from dfns
```
Comment (marcoscaceres) [inline tests/spec/core/anchor-expander-spec.js:81]:
```suggestion
    // title gets dropped from dfns
```

**Review by sidvishnoi — APPROVED** [review]
