### PR TITLE
fix(core/issue-notes) Improve GitHub issue labels

### LINKED ISSUE #1582: Improve github labels
Github labels are showing up, and they are awesome. Some improvements we could make:

- [x] cache issues (critical - we only get 60 requests / hour on Github)
- [x] concurrent download of issues (critical). The current design awaits each issue. 
- [ ] wrap them in an unordered list (`<ul>`). 
- [x] add an aria label, so this reads: "This issue is labelled on github as: x, y, and z". 
- [x] remove or improve hover effect... currently it's getting inherited, and it's a little bit too much. 

cc @himanish-star

### PR DESCRIPTION
**Pull request by pradeepgangwar**
What has been done:
- [x] Removed hover effect
- [x] Added aria-label to issue title that read "This issues is labelled as x,y"

Fixes #1582

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@marcoscaceres Please review.

File: src/core/issues-notes.js [hunk 1]
```diff
@@ -241,10 +241,15 @@ function isLight(rgb) {
...
 function createLabelsGroup(labels, title, repoURL) {
   const labelsGroup = labels.map(label => createLabel(label, repoURL));
+  const labelName = labels.map(label => label.name);
   if (labelsGroup.length) {
     labelsGroup.unshift(document.createTextNode(" "));
   }
-  return hyperHTML`<span style='text-transform: none'>: ${title}${labelsGroup}</span>`;
+  const ariaLabel = `This issue is labelled as ${labelName}`;
+  return hyperHTML`<span
+    style="text-transform: none"
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: While we are here, it would be nice to move this to the style sheet.

File: src/core/issues-notes.js [hunk 2]
```diff
@@ -241,10 +241,15 @@ function isLight(rgb) {
  */
 function createLabelsGroup(labels, title, repoURL) {
   const labelsGroup = labels.map(label => createLabel(label, repoURL));
+  const labelName = labels.map(label => label.name);
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: I think this will  be "x,y,z"? What we want is "x, y, and z" (i.e., spaces). You could use `ListFormat`, if it's available (supported in Chrome):
 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat

And .reduce() if not supported (Firefox for now).

File: src/core/issues-notes.js [hunk 3]
```diff
@@ -241,10 +241,15 @@ function isLight(rgb) {
...
   if (labelsGroup.length) {
     labelsGroup.unshift(document.createTextNode(" "));
   }
-  return hyperHTML`<span style='text-transform: none'>: ${title}${labelsGroup}</span>`;
+  const ariaLabel = `This issue is labelled as ${labelName}`;
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: as above... We should localize this string.

File: src/core/issues-notes.js [hunk 4]
```diff
@@ -239,12 +241,24 @@ function isLight(rgb) {
  * @param {string} title
  * @param {string} repoURL
  */
-function createLabelsGroup(labels, title, repoURL) {
+function createLabelsGroup(conf, labels, title, repoURL) {
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: Is `conf` used?

File: src/core/issues-notes.js [hunk 5]
```diff
@@ -239,12 +241,24 @@ function isLight(rgb) {
...
   const labelsGroup = labels.map(label => createLabel(label, repoURL));
+  let labelName = labels.map(label => label.name);
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: This should be `const`, for the final string, create a new variable. That avoids doing a type change. 

```suggestion
  const labelNames = labels.map(label => label.name);
```

File: src/core/issues-notes.js [hunk 6]
```diff
@@ -239,12 +241,24 @@ function isLight(rgb) {
...
+  const totalLabels = labels.length;
+  const reducer = (string, label, index) => {
+    return index === totalLabels - 1
+      ? `${string} and ${label}`
+      : `${string}, ${label}`;
+  };
+  labelName = labelName.reduce(reducer);
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: Oh, apologies, it occurred to me that we have a util function you can import for this: 

https://github.com/w3c/respec/blob/develop/src/core/utils.js#L382

After importing it you can just do:

```JS
const labels = joinAnd(labelNames);
```

File: src/core/issues-notes.js [hunk 7]
```diff
@@ -239,12 +241,24 @@ function isLight(rgb) {
...
   if (labelsGroup.length) {
     labelsGroup.unshift(document.createTextNode(" "));
   }
-  return hyperHTML`<span style='text-transform: none'>: ${title}${labelsGroup}</span>`;
+  const ariaLabel = `This issue is labelled as ${labelName}`;
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]:
```suggestion
  const ariaLabel = `This issue is labelled as ${labelNames}.`;
```

File: src/core/issues-notes.js [hunk 8]
```diff
@@ -241,10 +241,16 @@ function isLight(rgb) {
  */
 function createLabelsGroup(labels, title, repoURL) {
   const labelsGroup = labels.map(label => createLabel(label, repoURL));
+  let labelNames = labels.map(label => label.name);
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: please see my previous comments. Try not to switch data types (i.e., always use `const`).

File: src/core/issues-notes.js [hunk 9]
```diff
@@ -241,10 +241,16 @@ function isLight(rgb) {
...
+  labelNames = joinAnd(labelNames);
   if (labelsGroup.length) {
     labelsGroup.unshift(document.createTextNode(" "));
   }
-  return hyperHTML`<span style='text-transform: none'>: ${title}${labelsGroup}</span>`;
+  const ariaLabel = `This issue is labelled as ${labelNames}`;
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]: I think we need a full stop here, right? 
```suggestion
  const ariaLabel = `This issue is labelled as ${labelNames}.`;
```

File: src/core/issues-notes.js [hunk 10]
```diff
@@ -241,10 +241,16 @@ function isLight(rgb) {
  */
 function createLabelsGroup(labels, title, repoURL) {
   const labelsGroup = labels.map(label => createLabel(label, repoURL));
+  let labelNames = labels.map(label => label.name);
+  labelNames = joinAnd(labelNames);
```
Comment (marcoscaceres) [inline src/core/issues-notes.js]:
```suggestion
  const joinedNames = joinAnd(labelNames);
```

**Comment by pradeepgangwar** [comment]
Did the changes. I will write a test for it. :)

File: src/core/issues-notes.js (hunk 10 above)
Comment (pradeepgangwar) [reply src/core/issues-notes.js]: Done. :)

**Comment by marcoscaceres** [comment]
Excellent. Appreciate your work on this!

**Comment by pradeepgangwar** [comment]
@marcoscaceres Added a test for checking aria-label.
It got delayed because I had some examinations in university.

File: tests/spec/core/issues-notes-spec.js [hunk 11]
```diff
@@ -267,6 +267,32 @@ describe("Core — Issues and Notes", () => {
     );
   });
 
+  it("check if aria-label renders for issues", async () => {
```
Comment (marcoscaceres) [inline tests/spec/core/issues-notes-spec.js]:
```suggestion
  it("sets aria-label to reflect the labels from Github", async () => {
```

File: tests/spec/core/issues-notes-spec.js [hunk 12]
```diff
@@ -267,6 +267,32 @@ describe("Core — Issues and Notes", () => {
...
+    };
+    const ops = {
+      config: githubConfig,
+      body: `${makeDefaultBody()}
+        <div class='issue' data-number='1548'>no aria-label for this</div>
+        <div class='issue' data-number='1540'>this should have aria-label</div>
+      `,
+    };
+    const doc = await makeRSDoc(ops);
+    const issueDiv1 = doc.getElementById("issue-container-number-1548");
```
Comment (marcoscaceres) [inline tests/spec/core/issues-notes-spec.js]: We can probably make this a little more concise: 

```JS
expect(doc.querySelectorAll("div.issue").length).toBe(2);
expect(doc.querySelector(".issue[data-number=1548][aria-role]")).toBeNull();

const expectedAttributeValue = "This issue is labelled as refactor, bug, blank, and not-a-color.";
expect(doc.querySelector(`.issue[data-number=1540][aria-role=${expectedAttributeValue}]`)).toBeTruthy();
```

**Comment by pradeepgangwar** [comment]
@marcoscaceres Did the changes. Please review. :)
