### PR TITLE
fix(linter-rules/no-headingless-sections): don't warn if heading is unwrapped

### LINKED ISSUE #4039: addSectionLinks=false generates warnings
## Important info
See 
https://w3c.github.io/payment-request/?addSectionLinks=false

## Description of problem

**What happened (e.g., it crashed)?:**

addSectionLinks confuses one of the linters. 

**Expected behavior (e.g., it shouldn't crash):**

addSectionLinks shouldn't confuse the linter

**Optional, steps to reproduce:**

1.  Load https://w3c.github.io/payment-request/?addSectionLinks=false

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #4039

### CODE REVIEW

File: src/core/linter-rules/no-headingless-sections.js [hunk 1]
```diff
@@ -35,7 +35,10 @@ export function run(conf) {
     "section:not(.head,#abstract,#sotd)"
   );
   const offendingElements = [...sections].filter(
-    ({ firstElementChild: e }) => !e || !e.matches(".header-wrapper")
+    ({ firstElementChild: e }) =>
+      !e ||
+      // no header wrapper and the first child is not a heading
+      (!e.matches(".header-wrapper") && !(e instanceof HTMLHeadingElement))
```
Comment (sidvishnoi) [inline src/core/linter-rules/no-headingless-sections.js:41]: Nit:
```suggestion
      !(e.matches(".header-wrapper") || e instanceof HTMLHeadingElement)
```

**Review by sidvishnoi — APPROVED** [review]
