### PR TITLE
fix(core/markdown): use reindent() instead

### LINKED ISSUE #2609: Indentation is messed up in markdown code blocks
ReSpec version: 24.35.2

image
image

`normalizePadding` is causing troubles here.

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #2609

### CODE REVIEW

File: src/core/markdown.js [hunk 1]
```diff
@@ -233,6 +98,11 @@ function convertElements(selector) {
  * @param {Element} element
  */
 function convertElement(element) {
+  for (const pre of element.getElementsByTagName("pre")) {
+    // HTML parser implicitly removes a newline after <pre>
```
Comment (marcoscaceres) [inline src/core/markdown.js]: TIL
