### PR TITLE
fix(core/data-cite): avoid including self in bibliography

### LINKED ISSUE #1862: data-cite shouldn't create bibliography reference if citation is to shortName
## Important info

* URL to affected spec: https://w3c.github.io/json-ld-syntax/
* ReSpec version: 23.4.0
* [x] See example failing test

## Description of problem

JSON-LD 1.1 uses term definitions in common with related specs. An example term definition is the following:

```html
  <dt><dfn>context</dfn></dt><dd>
    A set of rules for interpreting a <a>JSON-LD document</a>
    as specified in <a data-cite="JSON-LD11#the-context">The Context</a> of the JSON-LD Syntax specification [[JSON-LD11]].</dd>
```

When `shortName` is configured to "json-ld11", it does turn the reference into a local reference, however it also adds a bibliography reference as well, and specs typically shouldn't reference themselves.

Here's a test that would be appropriate in data-cite-spec.js

```js
it(`does not create bibliography reference to itself`, async () => {
  const ops = {
    config: makeBasicConfig(),
    body:
      makeDefaultBody() +
      `
    <section>
      <h2>test</h2>
      <p>
        <a id="t1" data-cite="dahut#test">a</a>
      </p>
    </section>
  `,
  };
  ops.config.shortName = "dahut";
  const doc = await makeRSDoc(ops);
  const dahut = doc.getElementById("bib-dahut");
  expect(dahut).toBe(undefined);;
});
```

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #1862

### CODE REVIEW

File: tests/spec/core/data-cite-spec.js [hunk 1]
```diff
@@ -282,4 +282,25 @@ describe("Core — data-cite attribute", () => {
       ).toEqual("normative-references");
     });
   });
+
+  it("does not create bibliography reference to itself", async () => {
+    const ops = {
```
Comment (sidvishnoi) [inline tests/spec/core/data-cite-spec.js]:
```suggestion
    const body = `
      <section>
        <h2>test</h2>
        <p>
          <a data-cite="dahut#test">a</a>
          <a data-cite="DaHuT#test">a</a>
        </p>
      </section>
    `;
    const ops = makeStandardOps({ shortName: "dahut" }, body);
```

**Comment by marcoscaceres** [comment]
oh, nice, I didn't know you could do multi-line suggestions. I thought it was one liners. Need to check how to do that.

**Comment by sidvishnoi** [comment]
I thought you did delete and paste 😛
