### PR TITLE
fix(w3c): ensure w3c logo is present on TR docs

### LINKED ISSUE #3676: Don't allow W3C specs to override logo
## Description of problem

**What happened (e.g., it crashed)?:**

When declaring logos and the status is a W3C status, don't allow them to completely override the w3c logo.  

Also, logo's URLs should be resolved properly. Right now, they are treated as strings and resolved relative it seems.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #3676

### CODE REVIEW

File: tests/spec/w3c/headers-spec.js [hunk 1]
```diff
@@ -2103,8 +2103,30 @@ describe("W3C — Headers", () => {
...
+          {
+            src: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
+            alt: "Logo",
+            id: "logo",
+            url: "https://somewhere.else/",
+          },
+        ],
+      });
+      const doc = await makeRSDoc(ops);
+      expect(doc.querySelectorAll("a.logo")).toHaveSize(1);
```
Comment (sidvishnoi) [inline tests/spec/w3c/headers-spec.js:2126]: Let's also add a test for whether it's the correct logo.

**Review by sidvishnoi — APPROVED** [review]
