### PR TITLE
fix(w3c/headers): Add Preview of PR to title

### LINKED ISSUE #2030: Show "Preview of #" in title
See the following for details:
https://github.com/tobie/pr-preview/issues/23

Basically, the spec's title should come "Preview of PR xxx: " when the spec `isPreview` is true. 

This would build on @yatri1609's work: 
https://github.com/w3c/respec/pull/1843

### PR DESCRIPTION
**Pull request by Swapnilr1**
Fixes #2030 

This is how it looks: 
pr

Just confirm whether this is the intended fix and I will add a test for it.

### CODE REVIEW

File: tests/spec/w3c/headers-spec.js [hunk 1]
```diff
@@ -1408,4 +1408,13 @@ describe("W3C — Headers", () => {
...
     });
   });
+
+  it("adds Preview status to title", async () => {
+    const ops = makeStandardOps();
+    const doc = await makeRSDoc(
+      ops,
+      "spec/core/simple.html?isPreview=true&prNumber=123"
+    );
+    expect(doc.title).toBe("Preview of PR #123: Simple Spec");
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: And make sure the H1 is the same :)

File: src/w3c/headers.js [hunk 2]
```diff
@@ -273,7 +273,7 @@ export function run(conf) {
     }
   }
   const title = document.title || "No Title";
-  conf.title =
+  document.title = conf.title =
```
Comment (marcoscaceres) [inline src/w3c/headers.js]: We generally avoid the double assignments.

**Comment by marcoscaceres** [comment]
I would be really nice to also link the issue number in the H1... that will take the user back to the correct pull request on Github.

**Comment by Swapnilr1** [comment]
I need a small clarification here: Should we add "Preview of PR #" only if `isPreview`, `prNumber` and `prURL` all are configured or even when only `isPreview` and `prNumber` (so here no linking to the PR) are configured?

**Comment by Swapnilr1** [comment]
@marcoscaceres Is there a simpler way to prepend the text than what I have done?

File: src/w3c/headers.js [hunk 3]
```diff
@@ -273,6 +273,9 @@ export function run(conf) {
     }
   }
   conf.title = document.title || "No Title";
+  if (document.title && conf.isPreview && conf.prNumber) {
```
Comment (marcoscaceres) [inline src/w3c/headers.js]: I'm unsure about the first check for "document.title"?

File: src/w3c/templates/headers.js [hunk 4]
```diff
@@ -22,6 +22,20 @@ function getSpecTitleElem(conf) {
     specTitleElem.textContent = conf.title;
     specTitleElem.id = "title";
   }
+  if (conf.isPreview && conf.prNumber) {
+    if (conf.prUrl)
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: as a general rule, please always use "{" and "}" for multiline if statements.

File: src/w3c/templates/headers.js [hunk 5]
```diff
@@ -22,6 +22,20 @@ function getSpecTitleElem(conf) {
...
+      specTitleElem.prepend(
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: you could do:
```JS
 const {childNodes}  = html`Preview of PR <a href=${conf.prUrl}>#${conf.prNumber}</a>:`;
 specTitleElem.prepend(...childNodes);
```
And that gets rid of the span.

**Comment by marcoscaceres** [comment]
> I need a small clarification here: Should we add "Preview of PR #" only if isPreview, prNumber and prURL all are configured or even when only isPreview and prNumber (so here no linking to the PR) are configured?

We can ask that we always get the `prURL`, then we don't need to special case it.

File: src/w3c/templates/headers.js [hunk 6]
```diff
@@ -22,6 +22,20 @@ function getSpecTitleElem(conf) {
...
+        html`
+          <span
+            >Preview of PR <a href=${conf.prUrl}>#${conf.prNumber}</a>:
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]:
```suggestion
            >Preview of PR <a href="${conf.prUrl}">#${conf.prNumber}</a>:
```

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: As convention of the project, we like using the quotes for attributes (even if optional).

Comment (Swapnilr1) [reply src/w3c/templates/headers.js]: My bad, how did this even work at all when I was testing? :fearful:

File: src/w3c/headers.js (hunk 3 above)
Comment (Swapnilr1) [reply src/w3c/headers.js]: If I don't check this, and document.title is undefined, I would be setting document.title to be equal to "Preview of PR #XYZ: undefined". But if I leave it undefined when it is undefined, it would be set by  https://github.com/w3c/respec/blob/3c0dda705c7de88f6ec68a913d4b34d8126964d0/src/w3c/templates/headers.js#L27

File: src/w3c/templates/headers.js (hunk 5 above)
Comment (Swapnilr1) [reply src/w3c/templates/headers.js]: Can I use innerHTML instead? ESLint causes the the string to be split across lines, adding whitespace, which I cannot trim.

File: src/w3c/headers.js (hunk 3 above)
Comment (marcoscaceres) [reply src/w3c/headers.js]: ok, thanks for clarifying. I was unsure.

File: src/w3c/templates/headers.js (hunk 5 above)
Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: we prefer not to use `innerHTML` because hyperHTML gives us some security assurances. If you need to disable ESLint for a particular line, then that's acceptable. Just put a comment.

Comment (Swapnilr1) [reply src/w3c/templates/headers.js]: A comment asking not to remove the comment disabling eslint prettier?

File: tests/spec/w3c/headers-spec.js [hunk 7]
```diff
@@ -1408,4 +1408,42 @@ describe("W3C — Headers", () => {
...
+        },
+        body: `<h1 id='title'>Simple Spec</h1>${makeDefaultBody()}`,
+      };
+      const doc = await makeRSDoc(ops);
+      expect(doc.title).toBe("Preview of PR #123: Simple Spec");
+      const headingtitle = doc.querySelector("h1#title");
+      expect(headingtitle.textContent).toEqual(
+        "Preview of PR #123: Simple Spec"
+      );
+      expect(headingtitle.querySelector("a").href).toEqual(
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]:
```suggestion
      expect(headingtitle.querySelector("a").href).toBe(
```

File: tests/spec/w3c/headers-spec.js [hunk 8]
```diff
@@ -1408,4 +1408,42 @@ describe("W3C — Headers", () => {
...
+  describe("Add Preview Status in title", () => {
+    it("when document title is present", async () => {
+      const ops = makeStandardOps();
+      const doc = await makeRSDoc(
+        ops,
+        "spec/core/simple.html?isPreview=true&prNumber=123&prUrl=%22http%3A//w3c.github.io/respec/%22"
+      );
+      expect(doc.title).toBe("Preview of PR #123: Simple Spec");
+      const headingtitle = doc.querySelector("h1#title");
+      expect(headingtitle.textContent).toEqual(
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]:
```suggestion
      expect(headingtitle.textContent).toBe(
```

File: tests/spec/w3c/headers-spec.js [hunk 9]
```diff
@@ -1408,4 +1408,42 @@ describe("W3C — Headers", () => {
...
+          isPreview: true,
+          prNumber: 123,
+          prUrl: "http://w3c.github.io/respec/",
+        },
+        body: `<h1 id='title'>Simple Spec</h1>${makeDefaultBody()}`,
+      };
+      const doc = await makeRSDoc(ops);
+      expect(doc.title).toBe("Preview of PR #123: Simple Spec");
+      const headingtitle = doc.querySelector("h1#title");
+      expect(headingtitle.textContent).toEqual(
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]:
```suggestion
      expect(headingtitle.textContent).toBe(
```
