### PR TITLE
fix(w3c/headers): W3CNotes are /TR/ docs

### LINKED ISSUE #4064: Wrong syntax for This Version link
## Important info

- URL to affected spec: https://w3c.github.io/clreq/?specStatus=DNOTE
- ReSpec version: 31.0.9
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

Wrong syntax for This Version link.

**Expected behavior (e.g., it shouldn't crash):**

The syntax of a “this version” URI should be `https://www.w3.org/TR/YYYY/DNOTE-shortname-YYYYMMDD/` instead of `https://www.w3.org/TR/DNOTE-clreq-20220301/` (there is no year between `TR/` and `/DNOTE`).

**Steps to reproduce:**

1.  Open https://w3c.github.io/clreq/?specStatus=DNOTE
2. Observe the This Version link

### PR DESCRIPTION
**Pull request by marcoscaceres**
Also notes don't need a privacy and security considerations section. Only "specs" do.  

fixes #4064

### CODE REVIEW

File: tests/spec/w3c/linter-rules/required-sections-spec.js [hunk 1]
```diff
@@ -61,8 +61,8 @@ describe("w3c — required-sections", () => {
     expect(warnings).toHaveSize(2);
   });
 
-  it("doesn't lint non-rec-track docs", async () => {
-    for (const specStatus of [...noTrackStatus, "ED"]) {
+  for (const specStatus of [...noTrackStatus, "ED"]) {
```
Comment (sidvishnoi) [inline tests/spec/w3c/linter-rules/required-sections-spec.js:64]: Can we include "ED" in noTrackStatus?

**Review by sidvishnoi — APPROVED** [review]

File: tests/spec/w3c/linter-rules/required-sections-spec.js (hunk 1 above)
Comment (marcoscaceres) [reply tests/spec/w3c/linter-rules/required-sections-spec.js:64]: I'll look at doing that once I get around a rewriting the mess that is headers.js ... there were "special cases".
