### PR TITLE
fix(core/webidl): include optional's trivia

### LINKED ISSUE #1745: IDL Index looks too condensed
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/
* ReSpec version: 22.1.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

image

But what I was expecting?: Less condensed IDL definitions (spaces between definitions)

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #1745

### CODE REVIEW

File: tests/spec/core/webidl-spec.js [hunk 1]
```diff
@@ -669,6 +669,20 @@ partial dictionary AnotherThing {
...
   });
 
+  it("handles optional and trivia", () => {
+    const expected = `
+[Constructor(X x, optional Y y, /*trivia*/ Z y)]
+interface Foo {
+  void foo(X x, optional Y y, /*trivia*/ optional Z z);
+};
+callback CallBack = Z? (X x, optional Y y, /*trivia*/ optional Z z);
+    `.trim()
```
Comment (saschanaz) [inline tests/spec/core/webidl-spec.js]: nit: semicolon

**Comment by marcoscaceres** [comment]
+ respec@22.2.1
