### PR TITLE
fix(show-people): treat name as HTML

### LINKED ISSUE #1594: Language markup showing in Editors list
## Important info

* https://w3c.github.io/jlreq/
* ReSpec version: 20.3.0
* [ yes ] I did a "hard refresh", but it's still busted. 

## Description of problem

Expected: 

But what actually happened (the bug): Language-related markup showing through in Editors list.

screen shot 2018-03-28 at 08 07 37

### PR DESCRIPTION
**Pull request by marcoscaceres**
* fixes #1594

### CODE REVIEW

**Comment by marcoscaceres** [comment]
We need to add a test for this, but ran out of time. If anyone want to be a hero and add one, would be greatly appreciated. Otherwise, will do it tomorrow.

**Comment by OrionStar25** [comment]
I'll do it, I'm very free :smiley_cat:

File: src/w3c/templates/show-people.js [hunk 1]
```diff
@@ -7,19 +7,20 @@ export default (conf, name, items = []) => {
...
+    const personName = html`${{html: p.name}}`;
     const editorid = p.w3cid ? parseInt(p.w3cid, 10): null;
     const dd = html`<dd class='p-author h-card vcard'
       data-editor-id='${editorid}'></dd>`;
       const span = document.createDocumentFragment();
     const contents = [];
     if (p.mailto) {
       contents.push(html`<a class='ed_mailto u-email email p-name'
-        href='${`mailto:${p.mailto}`}'>${p.name}</a>`);
+        href='${`mailto:${p.mailto}`}'>${personName}</a>`);
```
Comment (saschanaz) [inline src/w3c/templates/show-people.js]: `${[p.name]}` should be enough to treat it as HTML.

https://viperhtml.js.org/hyperhtml/documentation/#essentials-8

>if it's an array of strings, they will be injected as explict opt-in for HTML

File: src/w3c/templates/show-people.js [hunk 2]
```diff
@@ -7,19 +7,20 @@ export default (conf, name, items = []) => {
   return results;
 
   function getItem(p, i) {
+    const personName = html`${{html: p.name}}`;
```
Comment (saschanaz) [inline src/w3c/templates/show-people.js]: How about `[p.name]`?

https://viperhtml.js.org/hyperhtml/documentation/#essentials-8

>if it's an array of strings, they will be injected as explict opt-in for HTML

Comment (marcoscaceres) [reply src/w3c/templates/show-people.js]: Good suggestion!

File: src/w3c/templates/show-people.js (hunk 1 above)
Comment (saschanaz) [inline src/w3c/templates/show-people.js]: We probably should just do inline `${[p.name]}`, otherwise the same text node will just change its parent three times.

Comment (marcoscaceres) [reply src/w3c/templates/show-people.js]: not sure I follow? Can you clarify?

**Comment by marcoscaceres** [comment]
@OrionStar25, thanks for offering to help.

The file you want to add tests to is: tests/spec/w3c/headers-spec.js

When testing, please use this config:

```JS
const opts = {
  editors: [
    {
      name:
        "<span lang='ja'>阿南 康宏</span> (Yasuhiro Anan), (<span lang='ja'>第１版</span> 1st edition)",
      company: "Microsoft",
    },
  ],
  formerEditors: [
    {
      name:
        "<span lang='ja'>阿南 康宏</span> (Yasuhiro Anan), (<span lang='ja'>第１版</span> 1st edition)",
      company: "Microsoft",
    },
  ],
};
```

And, eventually:

```JS
expect(editor.textContent).toEqual("阿南 康宏 (Yasuhiro Anan), (第１版 1st edition) (Microsoft)")
expect(formerEditor.textContent).toEqual("阿南 康宏 (Yasuhiro Anan), (第１版 1st edition) (Microsoft)")
```

**Comment by marcoscaceres** [comment]
Oh, and also check that the HTML element is there.

```
const firstSpan = editor.querySelector("span");
expect(firstSpan.lang).toBe("ja");
expect(firstSpan.textContent).toBe("阿南 康宏");

```

File: src/w3c/templates/show-people.js (hunk 1 above)
Comment (saschanaz) [reply src/w3c/templates/show-people.js]: Previous ``personName = html`${{html: p.name}}` `` creates a node, ``html`${personName}` `` adds it to another parent node, and then the same ``html`${personName}` `` moves the child node to a new parent (which means the previous parent loses a child), etc.

Now `personName` is not a node but an array so it's irrelevant 😁

Comment (marcoscaceres) [reply src/w3c/templates/show-people.js]: Ah, yeah... got it. Whoops. Ok, yeah, so `[]` is all round better.

**Comment by marcoscaceres** [comment]
@saschanaz, added tests. Awaiting your approval when you have time.

File: src/w3c/templates/show-people.js (hunk 1 above)
Comment (marcoscaceres) [reply src/w3c/templates/show-people.js]: See line 10 for `const personName = [p.name];`.

File: tests/spec/w3c/headers-spec.js [hunk 3]
```diff
@@ -180,6 +181,33 @@ describe("W3C — Headers", function() {
...
+          },
+        ],
+      };
+      const ops = makeStandardOps(config);
+      const doc = await makeRSDoc(ops);
+      const dtElems = [...doc.querySelectorAll(".head dt")];
+      const dtElem = dtElems.find(findEditor);
+      const ddElem = dtElem.nextElementSibling;
+      const [personName, edition] = ddElem.querySelectorAll(
+        "span>span:nth-child(1), span>span:nth-child(2)"
```
Comment (saschanaz) [inline tests/spec/w3c/headers-spec.js]: IMO `span>span` should be enough, but not a blocker.

**Comment by saschanaz** [comment]
It seems Codacy doesn't like the new single quote.

File: tests/spec/w3c/headers-spec.js (hunk 3 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: Good point. Will change it.

**Comment by marcoscaceres** [comment]
Huge thanks to @OrionStar25 for helping with the tests.

**Comment by marcoscaceres** [comment]
+ respec@20.5.1
