### PR TITLE
fix(core/data-abbr): normalize abbreviations

### LINKED ISSUE #2210: abbr title's whitespace needs normalization
As we are taking the taxtContent, we need to normalize the whitespace... otherwise, this happens:  

Screen Shot 2019-03-28 at 4 31 19 PM

### PR DESCRIPTION
**Pull request by devanshbatra04**
closes #2210

### CODE REVIEW

File: tests/spec/core/data-abbr-spec.js [hunk 1]
```diff
@@ -78,4 +78,15 @@ describe("Core — data-abbr", () => {
     const p = doc.getElementById("test");
     expect(p.classList).toContain("respec-offending-element");
   });
+  it("normalizes title of added abbr for unwanted spaces", async () => {
+    const ops = {
+      config: makeBasicConfig(),
+      body: `<section id="section">
+       <dfn id="test" data-abbr>Permanent Account \n   Number</dfn>
```
Comment (marcoscaceres) [inline tests/spec/core/data-abbr-spec.js]: Not evil enough  🦹‍♀️ 
```suggestion
       <dfn id="test" data-abbr>\t\n Permanent\t\nAccount \n   Number\t\n</dfn>
```

Comment (devanshbatra04) [reply tests/spec/core/data-abbr-spec.js]: Evil works for me.
