### PR TITLE
fix(w3c/sotd): allow CGs to prefer github coms

### LINKED ISSUE #1636: Comment filing in SOTD does not match W3M practice
It looks like W3M has started pointing to github instead of a mailing list as a means of submitting comments.

See SOTD at https://www.w3.org/TR/2018/REC-ttml-imsc1.0.1-20180424/

It does not look like this is supported by respec.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Plus adds "subscribe" to mailing list link that was missing for everyone. Looks like: 

Screen Shot 2021-02-17 at 6 15 55 pm

Closes #1636

### CODE REVIEW

File: src/w3c/templates/sotd.js [hunk 1]
```diff
@@ -425,14 +425,13 @@ function linkToCommunity(conf, opts) {
...
+          (<a href="${opts.mailToWGPublicListSubscription}">subscribe</a>,
+          <a
             href="${`https://lists.w3.org/Archives/Public/${conf.wgPublicList}/`}"
             >archives</a
           >)${conf.subjectPrefix
-            ? html`
-                with <code>${conf.subjectPrefix}</code> at the start of your
-                email's subject
-              `
+            ? html` with <code>${conf.subjectPrefix}</code> at the start of your
```
Comment (marcoscaceres) [inline src/w3c/templates/sotd.js:433]: this just fixes the whitespace... it was rendering as "emails' subject ."

**Review by sidvishnoi — APPROVED** [review]

**Review by sidvishnoi — APPROVED** [review]
