### PR TITLE
Fix (release.js): Protect against EPIPE bombs from npmjs (closes #645).

### LINKED ISSUE #645: node tools/release.js failing when uploading to npmjs
When I push a release, the command to push to npmjs times out.  When I check npmjs, the updated version is there.  So I am not sure what the issue is.  Below is a log file that it output the last time I tried:

> cat npm-debug.log.3995386276 
0 info it worked if it ends with ok
1 verbose cli [ '/home/ahby/.nvm/versions/node/v5.7.0/bin/node',
1 verbose cli   '/home/ahby/.nvm/versions/node/v5.7.0/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@3.6.0
3 info using node@v5.7.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/var/www/html/respec',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/ahby/.npm/respec/3.2.109/package.tgz not in flight; packing
9 verbose correctMkdir /home/ahby/.npm correctMkdir not in flight; initializing
10 info lifecycle respec@3.2.109~prepublish: respec@3.2.109
11 silly lifecycle respec@3.2.109~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/home/ahby/.npm/respec/3.2.109/package.tgz',
12 verbose tar pack   '/var/www/html/respec' ]
13 verbose tarball /home/ahby/.npm/respec/3.2.109/package.tgz
14 verbose folder /var/www/html/respec
15 verbose addLocalTarball adding from inside cache /home/ahby/.npm/respec/3.2.109/package.tgz
16 verbose correctMkdir /home/ahby/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd respec@3.2.109
18 verbose afterAdd /home/ahby/.npm/respec/3.2.109/package/package.json not in flight; writing
19 verbose correctMkdir /home/ahby/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /home/ahby/.npm/respec/3.2.109/package/package.json written
21 silly publish { name: 'respec',
21 silly publish   version: '3.2.109',
21 silly publish   license: 'W3C',
21 silly publish   description: 'Specification Edition Support Tool.',
21 silly publish   bin: { respec2html: './tools/respec2html.js' },
21 silly publish   repository: { type: 'git', url: 'git://github.com/w3c/respec.git' },
21 silly publish   author: { name: 'Robin Berjon' },
21 silly publish   devDependencies:
21 silly publish    { async: '^1.5.2',
21 silly publish      chai: '^3.5.0',
21 silly publish      colors: '^1.1.2',
21 silly publish      express: '^4.13.4',
21 silly publish      'fs-extra': '^0.26.5',
21 silly publish      'fs-promise': '^0.5.0',
21 silly publish      handlebars: '^4.0.5',
21 silly publish      'jasmine-core': '^2.4.1',
21 silly publish      'jasmine-reporters': '^2.1.1',
21 silly publish      jquery: '^2.2.1',
21 silly publish      jscs: '^2.11.0',
21 silly publish      jshint: '^2.9.1',
21 silly publish      karma: '^0.13.22',
21 silly publish      'karma-chrome-launcher': '^0.2.2',
21 silly publish      'karma-detect-browsers': '^2.0.2',
21 silly publish      'karma-firefox-launcher': '^0.1.7',
21 silly publish      'karma-ie-launcher': '^0.2.0',
21 silly publish      'karma-jasmine': '^0.3.7',
21 silly publish      'karma-mocha': '^0.2.2',
21 silly publish      'karma-mocha-reporter': '^2.0.0',
21 silly publish      'karma-opera-launcher': '^0.3.0',
21 silly publish      'karma-requirejs': '^0.2.5',
21 silly publish      'karma-safari-launcher': '^0.1.1',
21 silly publish      'karma-verbose-summary-reporter': '0.0.1',
21 silly publish      'marcosc-async': '^1.1.3',
21 silly publish      mocha: '^2.4.5',
21 silly publish      moment: '^2.12.0',
21 silly publish      'mozilla-download': '^1.1.1',
21 silly publish      'phantomjs-prebuilt': '^2.1.5',
21 silly publish      'promise-polyfill': '^3.1.0',
21 silly publish      prompt: '^1.0.0',
21 silly publish      requirejs: '^2.1.22',
21 silly publish      webidl2: '^2.0.11' },
21 silly publish   scripts:
21 silly publish    { karma: 'karma start --single-run',
21 silly publish      'test:karma': 'npm run karma',
21 silly publish      'test:headless': 'node ./tests/headless.js',
21 silly publish      'test:build': 'mocha ./tests/test-build.js',
21 silly publish      test: 'npm run test:headless; npm run test:karma',
21 silly publish      jshint: 'jshint karma.conf.js tests tools',
21 silly publish      jscs: 'jscs --esnext tests tools',
21 silly publish      'jscs:fix': 'jscs --esnext --fix tests',
21 silly publish      pretest: 'npm run jshint && npm run jscs',
21 silly publish      'test:travis': 'npm run pretest; npm run test:build; karma start --single-run --reporters progress karma.conf.js; npm run test:headless' },
21 silly publish   readme: '# ReSpec\n\n[Build Status](https://travis-ci.org/w3c/respec)\n\nReSpec is a JS library that makes it easier to write technical specifications, or documents\nthat tend to be technical in nature in general. It was originally designed for the purpose\nof writing W3C specifications, but has since grown to be able to support other outputs as\nwell.\n\n## Getting started\n\nIf you are just interested in writing a spec, you can grab the [starter spec](examples/starter.html).\n\n** You don\'t need to check-out or fork this repository.**\n\nIf you are new to spec writing, we strongly encourage you to read:\n\n  * [API Design Principles](https://w3ctag.github.io/design-principles/)\n  * [Writing Promise-Using Specifications](http://www.w3.org/2001/tag/doc/promises-guide)\n  * [Privacy and Security Self-Review Questionnaire](https://w3ctag.github.io/security-questionnaire/)\n\n## Getting help\n\nIf you experience issues, please email [spec-prod@w3.org](mailto:spec-prod@w3.org) or\nif you think something is broken, [file a bug](https://github.com/w3c/respec/issues).\n\n**Please note:** ReSpec is not endorsed by W3C and nobody should expect the W3C Webmaster to provide advice on\nproblems encountered with ReSpec, or on why it may be failing to produce pubrules-compliant\ncontent.\n\n## Bibliographical references\n\nBibliographical references have been moved out of ReSpec. You want to use\n[speref.org](http://www.specref.org/).\n\n## Want to see complete documentation?\n\n[Documentation for ReSpec](http://www.w3.org/respec) is available. Also see\nthe [documentation repository](https://github.com/w3c/respec-docs) for the sources.\n\n## Contribute\nSee our [contribution guidelines](.github/CONTRIBUTOR.md).\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: '1e5523de00b03f1f2e1de5ba89c0719a93fd26e9',
21 silly publish   bugs: { url: 'https://github.com/w3c/respec/issues' },
21 silly publish   homepage: 'https://github.com/w3c/respec#readme',
21 silly publish   _id: 'respec@3.2.109',
21 silly publish   _shasum: '7f715bf0f4d18f129f8b9b800a83a7f1cec7eae4',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name respec
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/respec
27 verbose publish registryBase https://registry.npmjs.org/
28 silly publish uploading /home/ahby/.npm/respec/3.2.109/package.tgz
29 verbose request uri https://registry.npmjs.org/respec
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 6:31:52 PM
32 verbose request using bearer token for auth
33 verbose request id e5313fbc7c29b699
34 http request PUT https://registry.npmjs.org/respec
35 http 200 https://registry.npmjs.org/respec
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   'content-length': '16',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Fri, 11 Mar 2016 18:32:03 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-iad2120-IAD',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1457721113.021606,VS0,VE10810' }
37 verbose request invalidating /home/ahby/.npm/registry.npmjs.org/respec on PUT
38 info lifecycle respec@3.2.109~publish: respec@3.2.109
39 verbose stack Error: write EPIPE
39 verbose stack     at exports._errnoException (util.js:856:11)
39 verbose stack     at WriteWrap.afterWrite (net.js:767:14)
40 verbose cwd /var/www/html/respec
41 error Linux 4.4.0-x86_64-linode63
42 error argv "/home/ahby/.nvm/versions/node/v5.7.0/bin/node" "/home/ahby/.nvm/versions/node/v5.7.0/bin/npm" "publish"
43 error node v5.7.0
44 error npm  v3.6.0
45 error code EPIPE
46 error errno EPIPE
47 error syscall write
48 error write EPIPE
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

### PR DESCRIPTION
**Pull request by marcoscaceres**
* Adds epipebomb package, which swallows EPIPE errors.
 * Adds a default timeout to `toExecPromise`, and the ability to override it.
 * Increases timeout for npm publish.

### CODE REVIEW

File: tools/release.js [hunk 1]
```diff
@@ -214,4 +222,4 @@ async.task(function * () {
   () => process.exit(0)
 ).catch(
   err => console.error(err)
-);
+);
```
Comment (halindrome) [inline tools/release.js]: No newline at end of file?

**Comment by marcoscaceres** [comment]
my editor decided to eat new lines at the end of docs :/

**Comment by halindrome** [comment]
huh.  ok.  LGTM.  no real way for me to test it except to attempt a node tools/release.js when we are ready

**Comment by marcoscaceres** [comment]
@halindrome that's how we roll, "test release in release!" we are :cow:+:boy:z!
