### PR TITLE
fix(w3c/templates/headers): use <h1> exists for title (fixes #460)

### LINKED ISSUE #460: problems generating h1 from title
http://w3c.github.io/clreq/ (and its TR equivalen) needs to add markup to the `h1` to apply language information, (a) so that chinese fonts are used for the ideographs, and (b) to enable the language in the title to be filtered by language.

since the `title` element takes only plain text, generating the `h1` from it, as respec does, is problematic.

i can think of other scenarios where you might possibly want to style the `h1` text, for just one example. see the `h1` for http://www.w3.org/International/questions/qa-navigation-select

can someone please de-couple this arrangement if there is an `h1` defined in the document already.

### PR DESCRIPTION
**Pull request by shikhar-scs**
> Note that the title of the document is reused as the title of the specification in the resulting document's h1. It's a small win, but that's always something less to repeat.

mentioned here, https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#the-very-basics .The same was to be rectified.

Suggested by @marcoscaceres, I've made some changes and pushed them here. Please review.
@saschanaz 

P.S. I'm clueless about the build errors :cry:

### CODE REVIEW

File: src/w3c/templates/headers.js [hunk 1]
```diff
@@ -7,7 +7,12 @@ export default conf => {
   const html = hyperHTML;
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title' property='${conf.doRDFa ? "dcterms:title" : null}'>${conf.title}</h1>
+  <script>
+    if (document.querySelectorAll("h1") ?
+      document.write("") :
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: So, here we want to get just the first, so `const h1 = querySelector(“body>h1”)`.

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: We want to avoid document.write (we are actually trying to remove it from the web entirely). It’s not allowed in many security contexts and has a huge performance penalty. 

Instead, use either the found h1, or just use the current code.

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Will provide you with some code suggestions once I’m back in front of a computer.

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: > Will provide you with some code suggestions once I’m back in front of a computer

Fine I'll wait. 👍 Also, please check  Slack whenever you are free

**Comment by shikhar-scs** [comment]
@marcoscaceres any updates ?

**Comment by marcoscaceres** [comment]
No, sorry... super busy still and about to jump on another plane. But should be as simple as:

```js
const h1 = querySelector(“h1#title, body>h1”);
if(h1){
   conf.specTile = h1.textContent.trim();
   // set attributes if required to do so...  
   h1.classList.add('title') 
   h1.id = "title";
} else {
  // whatever is currently in ReSpec
}
```

**Comment by marcoscaceres** [comment]
Note that we removed the `property` attribute, etc. so this will need a rebase.

**Comment by shikhar-scs** [comment]
Thanks @marcoscaceres for finding time in this busy schedule. I have made the required changes so you can review them whenever you are free :sweat_smile:

File: src/w3c/templates/headers.js [hunk 2]
```diff
@@ -7,7 +7,20 @@ export default conf => {
   const html = hyperHTML;
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
+  <script>
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: Not quite right. You need to look at what the `html` tagged template string is doing 😉 

We definitely don’t want a `script` element here.

**Comment by shikhar-scs** [comment]
@marcoscaceres Is this what you were expecting ?

BTW, I also tried 
```
${document.querySelector("h1#title, body>h1") ?
        const h1 = document.querySelector("h1#title, body>h1"),
        conf.specTile = h1.textContent.trim(),
        h1.classList.add("title"),
        h1.id = "title"
          :html`<h1 class="title p-name">${conf.title}</h1>`}

```

However, `const` didn't work with a ternary operator so I had to go with this. :sweat_smile: . Please suggest any more changes, if the need be. :smile:

**Comment by marcoscaceres** [comment]
@shikhar-scs, sorry, I wasn't very clear in the code sample I sent the other day... I was trying to illustrate the logic, but not exactly the solution. Where the code goes in relation to the template string doesn't matter too much (like, it could be a function call that returns the `h1` element).  

Having a look now at your latest changes.

File: src/w3c/templates/headers.js [hunk 3]
```diff
@@ -7,7 +7,13 @@ export default conf => {
   const html = hyperHTML;
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
+  
+  ${document.querySelector("h1#title, body>h1") ? (
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: Above the `return html` line, you could have a check for `const specTitleElem = document.querySelector("h1#title, body>h1")` or just create a HTML element if it's missing... then:

```JS
const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1") ;
if (specTitleElem.parentElement) { // remove it from the DOM tree, because we are going to relocate it
  specTitleElem.remove();
}
docorateSpecTitle(specTitleElem);
return html`<div class='head'>
    ${conf.logos.map(showLogo)}		    ${conf.logos.map(showLogo)}
    ${specTitleElem}
```

And `function docorateSpecTitle()` would check or add the `title` css class, `id` attribute, and whatever else is needed. 

The goal is never to repeat ourselves ([DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) and our goal is always to make code as legible and efficient as possible... note your original code has "document.querySelector" 3x times for the same thing, which is not ideal - both because it's hard to read, and because it's very inefficient to ask the browser to perform the query.   

Makes sense? Again, I don't know if the above code I proposed works - it's probably buggy (thus we need test for it), but should be hopefully enough to go from.

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: This is an awesome review! I'll make the changes accordingly. And yeah, [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by shikhar-scs** [comment]
@marcoscaceres I've pushed in some changes. This ensures that if an `<h1>` tag already exists, then it is the one to be kept. Otherwise, a new one is generated and used.

File: src/w3c/templates/headers.js [hunk 4]
```diff
@@ -43,12 +55,12 @@ export default conf => {
...
     ${conf.showPreviousVersion ? html`
       <dt>Previous version:</dt>
-      <dd><a href='${conf.prevVersion}'>${conf.prevVersion}</a></dd>
+      <dd><a rel='${conf.doRDFa ? "dcterms:replaces" : null}' href='${conf.prevVersion}'>${conf.prevVersion}</a></dd>
     ` : ""}
     ${conf.prevRecURI ? html`
       ${conf.isRec ? html`
           <dt>Previous Recommendation:</dt>
-          <dd><a href='${conf.prevRecURI}'>${conf.prevRecURI}</a></dd>
+          <dd><a rel='${conf.doRDFa ? "dcterms:replaces" : null}' href='${conf.prevRecURI}'>${conf.prevRecURI}</a></dd>
```
Comment (saschanaz) [inline src/w3c/templates/headers.js]: You may want to remove these `rel` and `property` things, as the main branch removed them. (See #1503)

File: src/w3c/templates/headers.js [hunk 5]
```diff
@@ -5,13 +5,25 @@ import showLink from "./show-link";
...
+    specTitleElem.classList.add("title", "p-name");
+    specTitleElem.id = "title";
+  }
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
+  ${specTitleElem}
   ${conf.subtitle ? html`
-    <h2 id='subtitle'>${conf.subtitle}</h2>
+    <h2 property='${conf.doRDFa ? "bibo:subtitle" : null}' id='subtitle'>${conf.subtitle}</h2>
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: nit: seems your rebase has re-introduced the `doRDFa` stuff... we recently removed that.

File: src/w3c/templates/headers.js [hunk 6]
```diff
@@ -5,13 +5,25 @@ import showLink from "./show-link";
...
   ` : ""}
-  <h2>${conf.prependW3C ? `W3C ` : ""}${conf.textStatus} <time class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
+  <h2>${conf.prependW3C ? `W3C ` : ""}${conf.textStatus} <time property='${conf.doRDFa ? "dcterms:issued" : null}' class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: as above, and same below

File: src/w3c/templates/headers.js [hunk 7]
```diff
@@ -5,13 +5,25 @@ import showLink from "./show-link";
...
   const html = hyperHTML;
+  const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1") ;
+  if (specTitleElem.parentElement) { // remove it from the DOM tree, because we are going to relocate it
+    specTitleElem.remove();
+    specTitleElem.innerText.trim();
+  } else {
+    specTitleElem.innerText = conf.title;
+  }
+  decorateSpecTitle(specTitleElem);
+  function decorateSpecTitle(specTitleElem) {
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: nit: move this function outside this export block (above would be great).

File: src/w3c/templates/headers.js [hunk 8]
```diff
@@ -5,13 +5,25 @@ import showLink from "./show-link";
 
 export default conf => {
   const html = hyperHTML;
+  const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1") ;
+  if (specTitleElem.parentElement) { // remove it from the DOM tree, because we are going to relocate it
+    specTitleElem.remove();
+    specTitleElem.innerText.trim();
```
Comment (saschanaz) [inline src/w3c/templates/headers.js]: It should be `specTitleElem.innerText = specTitleElem.innerText.trim();` to be effective, but why should we do this? Also, I would prefer `textContent` which is a whole lot faster than `innerText`, [at least on some browsers](https://kellegous.com/j/2013/02/27/innertext-vs-textcontent/):

image

Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: I think here we want:

```JS
conf.specTitle = specTitleElem.innerText.trim(); 
```

File: src/w3c/templates/headers.js [hunk 9]
```diff
@@ -5,13 +5,25 @@ import showLink from "./show-link";
 
 export default conf => {
   const html = hyperHTML;
+  const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1") ;
+  if (specTitleElem.parentElement) { // remove it from the DOM tree, because we are going to relocate it
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: We have a potential conflict here... if `conf.specTitle` is set, then `conf.specTitle` should win... and we should emit a an error about duplicate titles.

File: src/w3c/templates/headers.js (hunk 8 above)
Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: We definitely don't want to rewrite the content BTW. See the original bug, as the whole point of this is to retain the custom markup in the `h1`.

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: @saschanaz good suggestion about accessing `.textContent` btw.

Comment (saschanaz) [reply src/w3c/templates/headers.js]: >We definitely don't want to rewrite the content BTW.

Right, I just had no idea about what the line does.

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: I think @shikhar-scs had overlooked that :) 

@shikhar-scs, be mindful that calling `.trim()` doesn't actually trim the `.textContent` - it returns a trimmed *copy* of whatever is in `.textContent`.

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Err.. I mean "innerText"... you know what I'm saying :)

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Yes yes I get your point. Thankyou @marcoscaceres and @saschanaz for this detailed review. Ill get started with the changes soon :sweat_smile:

**Comment by shikhar-scs** [comment]
@marcoscaceres & @saschanaz I've introduced new changes and it does what is intended. Here's a preview 

Look at the Line#20 in the editor. This is when the h1 exists
.
h1exists1

This is when it doesn't

h1exists2

File: src/w3c/templates/headers.js [hunk 10]
```diff
@@ -3,11 +3,25 @@ import showLogo from "./show-logo";
...
 import showLink from "./show-link";
 
+function decorateSpecTitle(specTitleElem) {
+  specTitleElem.classList.add("title", "p-name");
+  specTitleElem.id = "title";
+}
+
 export default conf => {
   const html = hyperHTML;
+  const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1");
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: We should actually just require `"h1#title"`.  That is, to use this, Editors should explicitly write: `<h1 id="title">Foo</h1> `. Other `h1` should be ignored.

File: src/w3c/templates/headers.js [hunk 11]
```diff
@@ -3,11 +3,25 @@ import showLogo from "./show-logo";
 import showPeople from "./show-people";
 import showLink from "./show-link";
 
+function decorateSpecTitle(specTitleElem) {
+  specTitleElem.classList.add("title", "p-name");
+  specTitleElem.id = "title";
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: given suggestion below, this line can go away, and we can drop `decorateSpecTitle()`, but keep `specTitleElem.classList.add("title", "p-name");` as it's the only thing we need to do to the `h1`.

File: src/w3c/templates/headers.js [hunk 12]
```diff
@@ -3,11 +3,25 @@ import showLogo from "./show-logo";
...
+}
+
 export default conf => {
   const html = hyperHTML;
+  const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1");
+  if (specTitleElem.parentElement) {
+    // remove it from the DOM tree, because we are going to relocate it
+    specTitleElem.remove();
+    conf.specTitle = specTitleElem.innerText.trim();
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: this should be `conf.title = `

File: src/w3c/templates/headers.js [hunk 13]
```diff
@@ -3,11 +3,25 @@ import showLogo from "./show-logo";
...
+  } else {
+    specTitleElem.innerText = conf.title;
+  }
+  decorateSpecTitle(specTitleElem);
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
+  ${specTitleElem}
   ${conf.subtitle ? html`
     <h2 id='subtitle'>${conf.subtitle}</h2>
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: We should support the same behaviour for `conf.subTitle` too - we just match on "h2#subtitle".

**Comment by marcoscaceres** [comment]
This is starting to take shape! @shikhar-scs, start thinking about tests too.

File: src/w3c/templates/headers.js [hunk 14]
```diff
@@ -3,11 +3,25 @@ import showLogo from "./show-logo";
...
+}
+
 export default conf => {
   const html = hyperHTML;
+  const specTitleElem = document.querySelector("h1#title, body>h1") || document.createElement("h1");
+  if (specTitleElem.parentElement) {
+    // remove it from the DOM tree, because we are going to relocate it
+    specTitleElem.remove();
+    conf.specTitle = specTitleElem.innerText.trim();
+  } else {
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: We need one more check here:
```js
if(document.title !== conf.title) {
   pub("warn", "The document's title and the `<title>` element differ.") 
}
```

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Done! What all should I check in testing. That if `h1` exists what all should be in place and vice versa ?

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Also how do I perform a test on the `title` ? Aren't the tests in `tests/spec/w3c/headers-spec.js` mean't for the specific code block of 
```html
<section id='sotd'><p>foo</p></section><section id='toc'></section>
```
Shall I make a different one ?

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: > Done! What all should I check in testing. That if h1 exists what all should be in place and vice versa ?

 Yes, exactly. Also, check that `conf.title` is correctly set.

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: > Also how do I perform a test on the `title` ? 

Unfortunately, we won't be able to check that one :( We have a bug for that #1084.

**Comment by shikhar-scs** [comment]
@marcoscaceres I've made changes for this and also introduced the changes for `subtitle`. Please have a look. 
I'll start writing tests in a while. I have a rough idea on how to do the same :+1: . Suggest changes please.

**Comment by marcoscaceres** [comment]
No problem, will fix the formatting before we merge.

**Comment by marcoscaceres** [comment]
Seems the fails being reported by Travis are legit. This is causing regressions in other modules - so we need to look into those.

**Comment by shikhar-scs** [comment]
I'll get back to this in a week's time. Exams are holding me up :sweat_smile:

**Comment by marcoscaceres** [comment]
No problem! Good luck with your exams @shikhar-scs!!! 🤓📖

File: src/w3c/templates/headers.js [hunk 15]
```diff
@@ -2,16 +2,40 @@ import "deps/hyperhtml";
...
+    if (document.title !== conf.title) {
+      pub("warn", "The document's title and the `<title>` element differ.");
+    }
+    specTitleElem.textContent = conf.title;
+    specTitleElem.id = "title";
+  }
+  specTitleElem.classList.add("title", "p-name");
+
+  const specSubTitleElem =
+    document.querySelector("h2#subtitle") || document.createElement("h2");
```
Comment (sidvishnoi) [inline src/w3c/templates/headers.js]: You might want to add create a `h2` for subtitle only if `conf.subtitle` is given. 

Saying this if we need the same test conditions to hold for `"handles missing subtitle"` in https://github.com/w3c/respec/blob/9ae571a97d9162316c011c4946b1b16a205d23ef/tests/spec/w3c/headers-spec.js#L224-L233

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Nice suggestion. Though I guess now we can do away with the keeping the subtitle optional as we are anyways adding the subtitle element by my code. whatsay @marcoscaceres  ?

Comment (sidvishnoi) [reply src/w3c/templates/headers.js]: If `conf.subtitle` is not specified and neither `h2#subtitle` is created by user, it creates an empty `<h2 id="subtitle"></h2>`. Might need to look into that too (although an empty `h2#subtitle` doesn't hurt)

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Prefer we don’t have empty elements, as they risk getting styled.

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: So I should only include a `subTitleElement` if it exists in `conf.subTitle` ?

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Yep, exactly.

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: ohk fine :+1:

**Comment by shikhar-scs** [comment]
@marcoscaceres I guess this is ready to merge.

P.S. if you could check slack :sweat_smile:

**Comment by marcoscaceres** [comment]
> @marcoscaceres I guess this is ready to merge. All tests pass

The code is still not right tho. I'll review in there.

File: src/w3c/templates/headers.js [hunk 16]
```diff
@@ -2,16 +2,43 @@ import "deps/hyperhtml";
...
+  }  
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
-  ${conf.subtitle ? html`
-    <h2 id='subtitle'>${conf.subtitle}</h2>
-  ` : ""}
-  <h2>${conf.prependW3C ? `W3C ` : ""}${conf.textStatus} <time class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
+  ${specTitleElem}
+  ${conf.subtitle ? specSubTitleElem : ""}
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: Here, don't we just want:

```JS
${specSubTitleElem}
```

If it's null, won't it just not get rendered?

File: tests/spec/w3c/headers-spec.js [hunk 17]
```diff
@@ -221,6 +221,25 @@ describe("W3C — Headers", function() {
     });
   });
 
+  describe("title", () => {
+    it("uses <h1> if already present", async () => {
+      const ops = makeStandardOps();
+      ops.body = "<h1 id='title'>Hello <code>World</code></h1>" + makeDefaultBody();
+      const doc = await makeRSDoc(ops);
+
+      const titleInHead = doc.querySelectorAll(".head .title.p-name");
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: why not query `"head h1"`? And then:

```
expect(titleInHead.classList.has("p-name")).toBe(true);
expect(titleInHead.id).toEqual("title");
```

File: tests/spec/w3c/headers-spec.js [hunk 18]
```diff
@@ -221,6 +221,25 @@ describe("W3C — Headers", function() {
...
+      expect(titleInHead.length).toEqual(1);
+
+      const title = doc.querySelectorAll(".title.p-name");
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: Same here... might be good to clarify exactly what's being tested here. .

File: tests/spec/w3c/headers-spec.js [hunk 19]
```diff
@@ -221,6 +221,25 @@ describe("W3C — Headers", function() {
...
+      expect(title.length).toEqual(1);
+
+      const unescapedHTML = doc.querySelectorAll("#title code");
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: What we probably want here is to test that the first child is code, and the textContent is "World"... though we should change it to "pass"

File: tests/spec/w3c/headers-spec.js [hunk 20]
```diff
@@ -221,6 +221,25 @@ describe("W3C — Headers", function() {
...
+      expect(unescapedHTML.length).toEqual(1);
+
+      expect(doc.getElementById("title").innerText).toEqual("Hello World");
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: This is doing the same work we did above.

File: tests/spec/w3c/headers-spec.js [hunk 21]
```diff
@@ -231,6 +250,19 @@ describe("W3C — Headers", function() {
       const doc = await makeRSDoc(ops);
       expect($("#subtitle", doc).length).toEqual(0);
     });
+    
+    it("uses existing h2#subtitle as subtitle", async () => {
+      const ops = makeStandardOps();
+      ops.body = "<h2 id='subtitle'>This is a pre existing subtitle</h2>" + makeDefaultBody();
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: Make sure you add another element (e.g., `<code>pass</code>`) inside the `h2`, as that's the purpose of the change.

Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: Sure. The other changes belong to @sidvishnoi I guess. So I hope he would correct them :+1:

Comment (sidvishnoi) [reply tests/spec/w3c/headers-spec.js]: @shikhar-scs on it.

File: tests/spec/w3c/headers-spec.js (hunk 18 above)
Comment (sidvishnoi) [reply tests/spec/w3c/headers-spec.js]:
``` js
const title = doc.querySelectorAll(".title.p-name");
expect(title.length).toEqual(1); // original h1#title is removed
```
not sure how can I make this clearer. any help?

Comment (sidvishnoi) [reply tests/spec/w3c/headers-spec.js]: would this one do? https://gist.github.com/sidvishnoi/e60fa8b991c163339e38f6293458a310

**Comment by shikhar-scs** [comment]
Made the changes.

File: tests/spec/w3c/headers-spec.js (hunk 18 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: Yep, that one is good.

**Comment by shikhar-scs** [comment]
@marcoscaceres if you could see for final :sweat_smile:

File: tests/spec/w3c/headers-spec.js [hunk 22]
```diff
@@ -231,6 +250,22 @@ describe("W3C — Headers", function() {
...
+      const ops = makeStandardOps();
+      ops.body = "<h2 id='subtitle'>This is a pre existing subtitle <code>pass</code></h2>" + makeDefaultBody();
+      
+      const doc = await makeRSDoc(ops);
+
+      const subTitleElement = doc.querySelectorAll("h2#subtitle");
+      expect(subTitleElement.length).toEqual(1);
+      
+      const [forInnerText] = subTitleElement;
+      expect(forInnerText.textContent).toEqual("This is a pre existing subtitle");
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: Travis is falling this because "pass" is missing:

> Expected 'This is a pre existing subtitle pass' to equal 'This is a pre existing subtitle'.

File: tests/spec/w3c/headers-spec.js [hunk 23]
```diff
@@ -221,6 +221,25 @@ describe("W3C — Headers", function() {
     });
   });
 
+  describe("title", () => {
+    it("uses <h1> if already present", async () => {
+      const ops = makeStandardOps();
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: I think we are missing a test checking the effect on `conf.title`. 

```JS
const { title } = doc.defaultView.respecConfig; 
expect(title).toEqual(...);
```

File: tests/spec/w3c/headers-spec.js [hunk 24]
```diff
@@ -231,6 +250,22 @@ describe("W3C — Headers", function() {
       const doc = await makeRSDoc(ops);
       expect($("#subtitle", doc).length).toEqual(0);
     });
+    
+    it("uses existing h2#subtitle as subtitle", async () => {
+      const ops = makeStandardOps();
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: As above, we are missing a test to check `conf.subtitle`.

File: tests/spec/w3c/headers-spec.js (hunk 23 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: note that here we want to be sure we hit both code paths for the if statement. So, we might actually need two independent tests: 

1. one with the `respecConfig.title` and `h1`
1. one without the `respecConfig.title` but with `h1`

Same applies to `subtitle`.

Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: Even I was thinkning about the same. But in the case of `subtitle` we do have a test for a missing `subtitle` and moreover the subtitle element is not mandatorily present on the doc. So, do we still need it in the case of `subtitile` ?

Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: > ...not mandatorily present on the doc. So, do we still need it in the case of subtitile ?

So, mostly we are interested in making sure we walk all code paths, and think of weird edge cases. Although we'd like to assume things about what will be common usage, things break when users do things we don't expect.

Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: To be clear, I'm particularly interested in this being tested:
https://github.com/w3c/respec/pull/1516/files#diff-ebb1a497c097951bb868645bd73ade4fR29

Comment (sidvishnoi) [reply tests/spec/w3c/headers-spec.js]: > we want to be sure we hit both code paths for the if statement

@marcoscaceres you mean one with `h1` and one without `h1`? and not (w/ and w/o `respecConfig.title`)
so that our tests will be "*uses `respecConfig.title` if `<h1>` not present*" and "*uses `<h1>` for title if already present*"?

File: src/w3c/templates/headers.js [hunk 25]
```diff
@@ -2,16 +2,42 @@ import "deps/hyperhtml";
...
+    if (document.title !== conf.title) {
+      pub("warn", "The document's title and the `<title>` element differ.");
+    }
+    specTitleElem.textContent = conf.title;
+    specTitleElem.id = "title";
+  }
+  specTitleElem.classList.add("title", "p-name");
+
+  let specSubTitleElem = null;
+  if (conf.subtitle) {
```
Comment (sidvishnoi) [inline src/w3c/templates/headers.js]: @shikhar-scs As you are using condition `if (conf.subtitle)`, if `conf.subtitle` is not set, then even if a `<h2 id="subtitle">SUB</h2>` is present, it won't be used (i.e. the subtitle won't appear in `.head`).
Please check. (https://i.imgur.com/AO1cmSG.png)

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Ohk. I'll see this in a while :+1:

File: tests/spec/w3c/headers-spec.js (hunk 23 above)
Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: > To be clear, I'm particularly interested in this being tested:
https://github.com/w3c/respec/pull/1516/files#diff-ebb1a497c097951bb868645bd73ade4fR29

I guess we can test for this here : 

https://github.com/shikhar-scs/respec/blob/e3ddc6f13af4d4a965f4b5f22944dda35e895caf/tests/spec/w3c/headers-spec.js#L270-L281

File: src/w3c/templates/headers.js (hunk 25 above)
Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: @sidvishnoi nice find. Definitely need add that as a test!

File: tests/spec/w3c/headers-spec.js (hunk 23 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: It's best to just leave the old tests and just add new ones (even if they overlap). Changing existing tests risks introducing new regressions.

Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: Ok I'll implement that. Also @marcoscaceres is there any way I could run only a single test. I mean I have to go to `http://localhost:8080/tests/SpecRunner.html` after every little change I make (and then it starts all over again ). So, is there any way I could run just a single test or test file ?

Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: Ah yeah, just put "f" in front of either `it(` or `describe(`. So:

```
fit();// "focus" this one
fdescribe(); // focus all these tests. 
```

You an also click spec in the results page, to only run the files associated with that spec.

Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: More info https://jasmine.github.io/2.1/focused_specs.html

Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: This is a life saviour. Earlier I used to sit for minutes just to see small changes. Thanks Marcos

Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: Feel your pain. Just remember to remove the `fdescribe` and `fit` when done. I've accidentally checked in a few of those ☺️.

File: src/w3c/templates/headers.js (hunk 25 above)
Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: In such cases should I then introduce `conf.subtitle` in the configs, based on the condition `if(!conf.subtitle && document.querySelector("h2#subtitle")` ? 
Or just keep a test to ensure that all of this is in place ?

File: tests/spec/w3c/headers-spec.js (hunk 23 above)
Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: Ok so this has been covered :+1:

File: src/w3c/templates/headers.js (hunk 25 above)
Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Both, I would say. But basically, the tests should guide the code. Just add sufficient tests to cover all possible situations. If nothing breaks, you are good :)

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Ok :+1:

**Comment by shikhar-scs** [comment]
@marcoscaceres Please have a look now :sweat_smile:

File: tests/spec/w3c/headers-spec.js [hunk 26]
```diff
@@ -250,19 +250,89 @@ describe("W3C — Headers", function() {
...
       ops.body = "<h2 id='subtitle'>This is a pre existing subtitle <code>pass</code></h2>" + makeDefaultBody();
+    
+      const doc = await makeRSDoc(ops);
       
+      const subTitleElement = doc.querySelectorAll("h2#subtitle");
+      expect(subTitleElement.length).toEqual(1);
+    
+      const confSubTitle = doc.defaultView.respecConfig.subtitle;
+    
+      if (confSubTitle) {
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: This can't be an `if` here. It must equal exactly one thing.

File: tests/spec/w3c/headers-spec.js [hunk 27]
```diff
@@ -250,19 +250,89 @@ describe("W3C — Headers", function() {
...
+        expect(confSubTitle).toEqual("This is a pre existing subtitle pass");
+      } else {
+        expect(confSubTitle).toEqual("");
+      }
+    
+      const [forInnerText] = subTitleElement;
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: I'm still not sure what "forInnerText" is? It's clearly an element, but this seems a strange/non-standard way to get at it? Can you help me understand this bit?

File: tests/spec/w3c/headers-spec.js (hunk 26 above)
Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: I get it. This `if` would vary for each of the 3 tests that I have introduced. Correct ?

File: tests/spec/w3c/headers-spec.js [hunk 28]
```diff
@@ -250,19 +250,89 @@ describe("W3C — Headers", function() {
...
+      const initialSubtitle = doc.defaultView.respecConfig.subtitle;
+      expect(initialSubtitle).toEqual("This is a pre existing subtitle pass")
+    
       const subTitleElement = doc.querySelectorAll("h2#subtitle");
       expect(subTitleElement.length).toEqual(1);
-      
+    
+      const confSubTitle = doc.defaultView.respecConfig.subtitle;
+    
+      if (confSubTitle) {
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: As above - tests should never have a conditional :)

File: tests/spec/w3c/headers-spec.js [hunk 29]
```diff
@@ -250,19 +250,89 @@ describe("W3C — Headers", function() {
...
+      const newProps = {
+        subtitle: "sub",
+      };
+    
+      Object.assign(ops.config, newProps);
+    
       const doc = await makeRSDoc(ops);
-
+    
+      const initialSubtitle = doc.defaultView.respecConfig.subtitle;
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: nit: calling this "initialSubtitle" makes it sound like it could change. Maybe just:

```JS
 const { subtitle } = doc.defaultView.respecConfig;
```

File: tests/spec/w3c/headers-spec.js [hunk 30]
```diff
@@ -250,19 +250,89 @@ describe("W3C — Headers", function() {
...
+      expect(initialSubtitle).toEqual("This is a pre existing subtitle pass")
+    
       const subTitleElement = doc.querySelectorAll("h2#subtitle");
       expect(subTitleElement.length).toEqual(1);
-      
+    
+      const confSubTitle = doc.defaultView.respecConfig.subtitle;
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: this will be the same as initialSubtitle.

File: tests/spec/w3c/headers-spec.js (hunk 29 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: If you want the actual "initial subtitle", that's "ops.config.subtitle", as that's the one you passed. 

So, somewhere:

```JS
expect(doc.defaultView.respecConfig.subtitle).toEqual(ops.config.subtitle)
```

File: tests/spec/w3c/headers-spec.js [hunk 31]
```diff
@@ -250,19 +250,89 @@ describe("W3C — Headers", function() {
...
+    });
+    
+    it("introduces conf.subtitle if it doesn't exist but h2#subtitle exists", async () => {
+      const ops = makeStandardOps();
+    
+      ops.body = "<h2 id='subtitle'>This is a pre existing subtitle <code>pass</code></h2>" + makeDefaultBody();
+    
+      const doc = await makeRSDoc(ops);
+    
+      const initialSubtitle = doc.defaultView.respecConfig.subtitle;
```
Comment (marcoscaceres) [inline tests/spec/w3c/headers-spec.js]: As above about initial subtitle

**Comment by shikhar-scs** [comment]
Thankyou for the immediate feedback. I'll get back to this ASAP

File: tests/spec/w3c/headers-spec.js (hunk 26 above)
Comment (marcoscaceres) [reply tests/spec/w3c/headers-spec.js]: Correct. If you need to split into multiple tests, that's totally ok.

File: tests/spec/w3c/headers-spec.js (hunk 27 above)
Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: This `forInnerText` is for checking the entire `innertext` of the subtitle element (normal text + text inside <code\> tags )at once. Now, I think it is becoming a bit repetitive to check this again and again. Shall I remove it ?

Also, I was in college at that time so the late reply :sweat_smile:

File: tests/spec/w3c/headers-spec.js (hunk 28 above)
Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: Sure :+1:

File: tests/spec/w3c/headers-spec.js (hunk 29 above)
Comment (shikhar-scs) [reply tests/spec/w3c/headers-spec.js]: I guess we don't need it now. But thanks for the information :sweat_smile:

**Comment by shikhar-scs** [comment]
@marcoscaceres Is this it ?

**Comment by marcoscaceres** [comment]
Did a couple of fixes directly on github... so no idea if it works. But I think that's closer to what we want.

File: src/w3c/templates/headers.js [hunk 32]
```diff
@@ -2,16 +2,42 @@ import "deps/hyperhtml";
...
+  } else {
+    if (document.title !== conf.title) {
+      pub("warn", "The document's title and the `<title>` element differ.");
+    }
+    specTitleElem.textContent = conf.title;
+    specTitleElem.id = "title";
+  }
+  specTitleElem.classList.add("title", "p-name");
+
+  let specSubTitleElem = document.querySelector("h2#subtitle");
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: This gives us `null` for free, which is nice.

File: src/w3c/templates/headers.js [hunk 33]
```diff
@@ -2,16 +2,42 @@ import "deps/hyperhtml";
...
+  if (specSubTitleElem && specSubTitleElem.parentElement) {
+    specSubTitleElem.remove();
+    conf.subtitle = specSubTitleElem.textContent.trim();
+  } else if (conf.subtitle) {
+    specSubTitleElem = document.createElement("h2");
+    specSubTitleElem.textContent = conf.subtitle;
+    specSubTitleElem.id = "subtitle";
+  }
+  if (specSubTitleElem) {
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: in either element case, but ignoring null...

**Comment by shikhar-scs** [comment]
> so no idea if it works

I'll pull for once and see.

**Comment by shikhar-scs** [comment]
> so no idea if it works

I'll pull for once and see.

**Comment by shikhar-scs** [comment]
Really thankful to you for all this painstaking work :clap: :sweat_smile: . Let's wait for saschanz then :+1:

File: src/w3c/templates/headers.js [hunk 34]
```diff
@@ -2,16 +2,42 @@ import "deps/hyperhtml";
 import showLogo from "./show-logo";
 import showPeople from "./show-people";
 import showLink from "./show-link";
+import { pub } from "core/pubsubhub";
 
 export default conf => {
   const html = hyperHTML;
+  const specTitleElem =
+    document.querySelector("h1#title") || document.createElement("h1");
```
Comment (saschanaz) [inline src/w3c/templates/headers.js]: Generally okay, but maybe we can split these into `getSpecTitleElement()` and `getSpecSubtitleElement()` functions for readability.

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: If I could get a confirmation on this it, I'll incorporate :sweat_smile:

File: src/w3c/templates/headers.js [hunk 35]
```diff
@@ -2,16 +2,42 @@ import "deps/hyperhtml";
...
   return html`<div class='head'>
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
-  ${conf.subtitle ? html`
-    <h2 id='subtitle'>${conf.subtitle}</h2>
-  ` : ""}
-  <h2>${conf.prependW3C ? `W3C ` : ""}${conf.textStatus} <time class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
+  ${specTitleElem}
+  ${specSubTitleElem}
+  <h2>${conf.prependW3C ? "W3C " : ""}${ conf.textStatus } <time class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
```
[the remark this answers is not in the document]
Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: Done :+1:

File: src/w3c/templates/headers.js (hunk 34 above)
Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Good idea about splitting this out into functions.

**Comment by shikhar-scs** [comment]
@marcoscaceres I've changed it to functions now. Please have a look. 

P.S. Also, if you could check slack for a while (I know you don't do it on saturdays but it would be great if you could see it for once )

File: src/w3c/templates/headers.js [hunk 36]
```diff
@@ -2,16 +2,50 @@ import "deps/hyperhtml";
 import showLogo from "./show-logo";
 import showPeople from "./show-people";
 import showLink from "./show-link";
+import { pub } from "core/pubsubhub";
 
 export default conf => {
   const html = hyperHTML;
+  
+  function getSpecTitleElem () {
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: These should be moved outside this function.

File: src/w3c/templates/headers.js [hunk 37]
```diff
@@ -2,16 +2,50 @@ import "deps/hyperhtml";
...
+        pub("warn", "The document's title and the `<title>` element differ.");
+      }
+      specTitleElem.textContent = conf.title;
+      specTitleElem.id = "title";
+    }
+    specTitleElem.classList.add("title", "p-name");
+    return specTitleElem;
+  }
+  
+  function getSpecSubTitleElem () {
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: As above

File: src/w3c/templates/headers.js [hunk 38]
```diff
@@ -2,16 +2,50 @@ import "deps/hyperhtml";
...
+    let specSubTitleElem = document.querySelector("h2#subtitle");
+    
+    if (specSubTitleElem && specSubTitleElem.parentElement) {
+      specSubTitleElem.remove ();
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: Nit: spaces before (). Also elsewhere.

File: src/w3c/templates/headers.js [hunk 39]
```diff
@@ -2,16 +2,50 @@ import "deps/hyperhtml";
...
   ${conf.logos.map(showLogo)}
-  <h1 class='title p-name' id='title'>${conf.title}</h1>
-  ${conf.subtitle ? html`
-    <h2 id='subtitle'>${conf.subtitle}</h2>
-  ` : ""}
-  <h2>${conf.prependW3C ? `W3C ` : ""}${conf.textStatus} <time class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
+  ${getSpecTitleElem()}
+  ${getSpecSubTitleElem()}
+  <h2>${conf.prependW3C ? "W3C":""}${conf.textStatus}<time class='dt-published' datetime='${conf.dashDate}'>${conf.publishHumanDate}</time></h2>
   <dl>
```
Comment (marcoscaceres) [inline src/w3c/templates/headers.js]: Please add a space to “W3C “. See TravisCI error.

**Comment by marcoscaceres** [comment]
I’m not on my computer today so can’t access slack (reviewing on my phone). Happy to answer questions on email tho.

File: src/w3c/templates/headers.js (hunk 36 above)
Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: I had initially kept these 2 functions outside the `export` statement only. However, `conf` would then be undefined and thus, 5 out of 6 tests fail :disappointed: . I guess we'll have to keep them inside `export` only

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Ah, you can just pass conf in:

```js
function getSpecTitleElem(conf) {

}
```

Comment (shikhar-scs) [reply src/w3c/templates/headers.js]: how can i miss that. So sorry

Comment (marcoscaceres) [reply src/w3c/templates/headers.js]: Heh, it happens to all of us :) why reviews matter.

**Comment by marcoscaceres** [comment]
Nice work @shikhar-scs!

**Comment by shikhar-scs** [comment]
yayy !!! Thanks a lot @marcoscaceres for merging this :tada:
