### PR TITLE
fix(w3c/seo): update list of docs that required canonical link

### LINKED ISSUE #3786: Canonical URL for TAG findings should not default to /TR/ space
## Important info

- URL to affected spec: https://w3ctag.github.io/ethical-web-principles/ 
- ReSpec version: ReSpec 26.13.4
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

Doing an export as HTML, it produces 
`<link rel="canonical" href="https://www.w3.org/TR/ethical-web-principles/">`
instead of 
`<link rel="canonical" href="https://www.w3.org/2001/tag/doc/ethical-web-principles/">`
Basically, the base URL should be `https://www.w3.org/2001/tag/doc/` instead of `https://www.w3.org/TR/` for TAG findings.
Cheers,

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #3786

### CODE REVIEW

File: tests/spec/w3c/seo-spec.js [hunk 1]
```diff
@@ -1,57 +1,93 @@
...
-    const test = makeTest("https://www.w3.org/TR/Foo/");
-    const ops = makeStandardOps();
-    ops.config.canonicalURI = "TR";
-    test(await makeRSDoc(ops));
+    const href = "https://www.w3.org/TR/Foo/";
+    const ops = makeStandardOps({ canonicalURI: "TR" });
+    const doc = await makeRSDoc(ops);
+    expect(
+      doc.querySelector(`link[rel='canonical'][href='${href}']`)
+    ).toBeTruthy();
```
Comment (sidvishnoi) [inline tests/spec/w3c/seo-spec.js:24]: Side note: Might be nice to have a custom jasmine matcher in future. Like:
```js
expect(`link[rel='canonical'][href='${href}']`).toBeInDocument(doc);
```

**Review by sidvishnoi — APPROVED** [review]

File: tests/spec/w3c/seo-spec.js (hunk 1 above)
Comment (marcoscaceres) [reply tests/spec/w3c/seo-spec.js:24]: oh! fancy! Didn't know we could do that.

Comment (sidvishnoi) [reply tests/spec/w3c/seo-spec.js:24]: Can't yet, but can [extend jasmine](https://jasmine.github.io/tutorials/custom_matcher).
