### PR TITLE
fix(core/issues-notes): closed issue should be removed from spec

### LINKED ISSUE #670: Issues that are closed shouldn't show up in the spec
With the GH module, when issues are closed, they still show up in the spec but as empty... they should be removed from the document and from the summary:

screenshot 2016-03-24 13 45 18

A warning should be generated instead.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #1506, fixes #670

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@saschanaz, to ignore whitespace: https://github.com/w3c/respec/pull/1570/files?w=1

File: src/core/issues-notes.js [hunk 1]
```diff
@@ -140,21 +152,30 @@ async function fetchIssuesFromGithub({ githubAPI }) {
     .map(elem => Number.parseInt(elem.dataset.number, 10))
     .filter(number => number);
   for (const issueNumber of issueNumbers) {
+    const issue = { title: "", number: issueNumber, status: "" };
```
Comment (saschanaz) [inline src/core/issues-notes.js]: Why should we set this and use `Object.assign`, instead of just using `response.json()`?

File: src/core/issues-notes.js [hunk 2]
```diff
@@ -140,21 +152,30 @@ async function fetchIssuesFromGithub({ githubAPI }) {
...
+          default:
+            throw new Error("Network error. Github is down? or too many requests?");
+        }
+      }
+      const json = await response.json();
+      Object.assign(issue, json);
     } catch (err) {
       console.error(err);
-      const msg = `There was an error fetching ${issueNumber} from GitHub. See developer console.`;
+      const msg = `Error fetching issue "${issueNumber}" from GitHub. ${err.message}. See developer console.`;
```
Comment (saschanaz) [inline src/core/issues-notes.js]: Not a big issue, but how about `#${issueNumber}` instead of `"${issueNumber}"`?

File: src/core/issues-notes.js (hunk 1 above)
Comment (marcoscaceres) [reply src/core/issues-notes.js]: I wanted to avoid creating the object twice, but probably ok to just assign it.

File: src/core/issues-notes.js (hunk 2 above)
Comment (marcoscaceres) [reply src/core/issues-notes.js]: yeah, that be nice.

File: src/core/issues-notes.js [hunk 3]
```diff
@@ -140,21 +152,30 @@ async function fetchIssuesFromGithub({ githubAPI }) {
...
+        }
+      }
+      issue = await response.json(); // can throw too
     } catch (err) {
       console.error(err);
-      const msg = `There was an error fetching ${issueNumber} from GitHub. See developer console.`;
+      const msg = `Error fetching issue #${issueNumber} from GitHub. ${err.message}. See developer console.`;
       pub("error", msg);
-      issues.push([issueNumber, { title: "" }]);
+      issue = { title: "", number: issueNumber, status: "" };
```
Comment (saschanaz) [inline src/core/issues-notes.js]: Maybe a typo of `state`?

**Comment by saschanaz** [comment]
A test is failing and it looks critical...

```
SUMMARY:
✔ 302 tests completed
✖ 1 test failed

FAILED TESTS:
  Core — Issues and Notes
    ✖ removes closed issues from spec
      HeadlessChrome 65.0.3325 (Linux 0.0.0)
    Expected <div class="" id="this-should-not-exist">...</div> to be falsy.
        at <Jasmine>
        at UserContext.it (tests/spec/core/issues-notes-spec.js:181:23)
```

**Comment by marcoscaceres** [comment]
ah, forgot to tell Karma about tests/data.

**Comment by marcoscaceres** [comment]
happy now 💃

**Comment by himanish-star** [comment]
Cool! 😃 . Shall I close #1506 in the favor of this

**Comment by marcoscaceres** [comment]
> Cool! 😃 . Shall I close #1506 in the favor of this?

No need. It will auto-close. 

@himanish-star, do you want to give this one last look over, and tick approved if you think it's ok?

**Comment by himanish-star** [comment]
Sure

**Comment by himanish-star** [comment]
Yep looks good to go 👍
