### PR TITLE
Fix(ui): close ui when doc is clicked (closes #772)

### LINKED ISSUE #772: Clicking on document should close pill
I think there was a regression with ReSpec pill. It no longer hides the drop down menu when clicking on the document.  You need to click on the pill again to close it.

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
r, please? 🍓

File: tests/spec/core/ui-spec.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 "use strict";
 
-describe("Core - Ui", function () {
+fdescribe("Core - Ui", function () {
```
Comment (marcoscaceres) [inline tests/spec/core/ui-spec.js]: D'oh

**Comment by marcoscaceres** [comment]
Rebased

**Comment by marcoscaceres** [comment]
Merging to avoid bit rot + it's a small fix.
