### PR TITLE
fix(core/contrib): remove [bot]s from gh contributors

### LINKED ISSUE #4169: gh-contributors list needs escaping
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/html-aam/

**What happened (e.g., it crashed)?:**

Outputs the following code
`<li><a href="https://github.com/github-actions[bot]">github-actions[bot]</a></li>`

**Expected behavior (e.g., it shouldn't crash):**
It should escape [bot] in the href so it passes the validator

**Optional, steps to reproduce:**

1.  ...

### PR DESCRIPTION
**Pull request by jnurthen**
Closes #4169

### CODE REVIEW

File: src/core/contrib.js [hunk 1]
```diff
@@ -54,7 +54,9 @@ async function showContributors(editors, apiURL) {
       /** @type {Contributor[]} */
       const contributors = await res.json();
       return contributors.filter(
-        user => !editors.includes(user.name || user.login)
+        user =>
+          !editors.includes(user.name || user.login) &&
+          !(user.login.indexOf("[bot]") > 0)
```
Comment (sidvishnoi) [inline src/core/contrib.js:59]:
```suggestion
          !user.login.includes("[bot]")
```

**Comment by jnurthen** [comment]
@sidvishnoi getting errors trying to run tests. Any ideas?

nurthen@Jamess-MacBook-Pro respec % npm start -- --interactive    

> respec@32.1.9 start /Users/nurthen/Documents/Dev/w3c/respec
> node ./tools/dev-server.js "--interactive"

(node:85587) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:666:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:85587) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:85587) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
